project_id = "pjfhkopecutrxebrfnqh"

[functions.admin-reset-password]
verify_jwt = false

[functions.agent-presence-update]
verify_jwt = false

[functions.ai-support-chat]
verify_jwt = false

[functions.capture-ip-action]
verify_jwt = false

[functions.chat-reassignment]
verify_jwt = false

[functions.check-admin-exists]
verify_jwt = false

[functions.confirm-user-email]
verify_jwt = false

[functions.create-first-admin]
verify_jwt = false

[functions.create-public-order]
verify_jwt = false

[functions.cj-product-search]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.get-client-ip]
verify_jwt = false

[functions.manage-admin]
verify_jwt = false

[functions.process-auto-payouts]
verify_jwt = false

[functions.process-wallet-payment]
verify_jwt = false

[functions.reset-user-data]
verify_jwt = false

[functions.send-chat-failure-notification]
verify_jwt = false

[functions.send-login-alert]
verify_jwt = false

[functions.send-mfa-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-postpaid-due-reminder]
verify_jwt = false

[functions.validate-ifsc]
verify_jwt = false

[functions.verify-crypto-payment]
verify_jwt = false
