import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa' | 'or';

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguage: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Base English translations - comprehensive
const enTranslations: Record<string, string> = {
  // Common
  'common.loading': 'Loading...',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.submit': 'Submit',
  'common.confirm': 'Confirm',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.refresh': 'Refresh',
  'common.close': 'Close',
  'common.view': 'View',
  'common.download': 'Download',
  'common.upload': 'Upload',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.actions': 'Actions',
  'common.status': 'Status',
  'common.date': 'Date',
  'common.amount': 'Amount',
  'common.total': 'Total',
  'common.details': 'Details',
  'common.success': 'Success',
  'common.error': 'Error',
  'common.warning': 'Warning',
  'common.info': 'Info',
  'common.all': 'All',
  'common.none': 'None',
  'common.select': 'Select',
  'common.clear': 'Clear',
  'common.apply': 'Apply',
  'common.reset': 'Reset',
  'common.update': 'Update',
  'common.create': 'Create',
  'common.add': 'Add',
  'common.remove': 'Remove',
  'common.copy': 'Copy',
  'common.share': 'Share',
  'common.export': 'Export',
  'common.import': 'Import',
  'common.print': 'Print',
  'common.active': 'Active',
  'common.inactive': 'Inactive',
  'common.enabled': 'Enabled',
  'common.disabled': 'Disabled',
  'common.pending': 'Pending',
  'common.approved': 'Approved',
  'common.rejected': 'Rejected',
  'common.completed': 'Completed',
  'common.failed': 'Failed',
  'common.processing': 'Processing',
  'common.from': 'From',
  'common.to': 'To',
  'common.by': 'By',
  'common.at': 'At',
  'common.on': 'On',
  'common.or': 'Or',
  'common.and': 'And',
  'common.of': 'Of',
  'common.new': 'New',
  'common.old': 'Old',
  'common.more': 'More',
  'common.less': 'Less',
  'common.show': 'Show',
  'common.hide': 'Hide',
  'common.required': 'Required',
  'common.optional': 'Optional',
  'common.copied': 'Copied!',
  'common.saved': 'Saved!',
  'common.updated': 'Updated!',
  'common.deleted': 'Deleted!',
  'common.created': 'Created!',
  
  // Navigation
  'nav.dashboard': 'Dashboard',
  'nav.profile': 'Profile',
  'nav.storefront': 'My Storefront',
  'nav.products': 'Browse Products',
  'nav.orders': 'Orders',
  'nav.payments': 'Payments',
  'nav.workspace': 'Workspace',
  'nav.support': 'Support',
  'nav.help': 'Help & FAQ',
  'nav.logout': 'Logout',
  'nav.settings': 'Settings',
  'nav.home': 'Home',
  'nav.chat': 'Chat',
  'nav.notifications': 'Notifications',
  'nav.kyc': 'KYC Verification',
  'nav.wallet': 'Wallet',
  'nav.crypto': 'Crypto Payments',
  'nav.ai': 'AI Assistant',
  'nav.admin': 'Admin Panel',
  'nav.users': 'Users',
  'nav.reports': 'Reports',
  'nav.payouts': 'Payouts',
  
  // Profile
  'profile.title': 'My Profile',
  'profile.description': 'View your profile information, security settings, and activity.',
  'profile.appearance': 'Appearance',
  'profile.appearance_desc': 'Choose your preferred theme for the dashboard',
  'profile.language': 'Language',
  'profile.language_desc': 'Select your preferred language',
  'profile.security': 'Security',
  'profile.change_password': 'Change Password',
  'profile.two_factor': 'Two-Factor Authentication',
  'profile.login_activity': 'Login Activity',
  'profile.account_info': 'Account Information',
  'profile.email': 'Email',
  'profile.name': 'Name',
  'profile.phone': 'Phone',
  'profile.address': 'Address',
  'profile.update_profile': 'Update Profile',
  'profile.profile_updated': 'Profile updated successfully',
  'profile.avatar': 'Profile Picture',
  'profile.bio': 'Bio',
  'profile.joined': 'Member since',
  'profile.level': 'Level',
  'profile.referral_code': 'Referral Code',
  
  // Auth
  'auth.login': 'Login',
  'auth.signup': 'Sign Up',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.forgot_password': 'Forgot Password?',
  'auth.remember_me': 'Remember me',
  'auth.welcome_back': 'Welcome back',
  'auth.sign_in_desc': 'Sign in to access your dashboard',
  'auth.email_address': 'Email address',
  'auth.create_account': 'Create Account',
  'auth.already_have_account': 'Already have an account?',
  'auth.dont_have_account': "Don't have an account?",
  'auth.verify_email': 'Verify Email',
  'auth.resend_code': 'Resend Code',
  'auth.verification_code': 'Verification Code',
  'auth.new_password': 'New Password',
  'auth.confirm_password': 'Confirm Password',
  'auth.reset_password': 'Reset Password',
  'auth.password_changed': 'Password changed successfully',
  'auth.invalid_credentials': 'Invalid email or password',
  'auth.account_created': 'Account created successfully',
  'auth.logout_success': 'Logged out successfully',
  'auth.session_expired': 'Session expired. Please login again.',
  
  // Dashboard
  'dashboard.welcome': 'Welcome back',
  'dashboard.total_orders': 'Total Orders',
  'dashboard.pending_orders': 'Pending Orders',
  'dashboard.wallet_balance': 'Wallet Balance',
  'dashboard.total_earnings': 'Total Earnings',
  'dashboard.recent_orders': 'Recent Orders',
  'dashboard.quick_actions': 'Quick Actions',
  'dashboard.view_all': 'View All',
  'dashboard.todays_sales': "Today's Sales",
  'dashboard.this_week': 'This Week',
  'dashboard.this_month': 'This Month',
  'dashboard.growth': 'Growth',
  'dashboard.revenue': 'Revenue',
  'dashboard.profit': 'Profit',
  'dashboard.commission': 'Commission',
  'dashboard.store_performance': 'Store Performance',
  'dashboard.order_analytics': 'Order Analytics',
  'dashboard.getting_started': 'Getting Started',
  'dashboard.watch_tutorial': 'Watch Tutorial',
  'dashboard.completed_orders': 'Completed Orders',
  'dashboard.cancelled_orders': 'Cancelled Orders',
  'dashboard.average_order_value': 'Average Order Value',
  'dashboard.conversion_rate': 'Conversion Rate',
  'dashboard.top_products': 'Top Products',
  'dashboard.recent_activity': 'Recent Activity',
  'dashboard.notifications': 'Notifications',
  'dashboard.announcements': 'Announcements',
  'dashboard.postpaid_credit': 'Postpaid Credit',
  'dashboard.available_credit': 'Available Credit',
  'dashboard.used_credit': 'Used Credit',
  'dashboard.due_amount': 'Due Amount',
  
  // Orders
  'orders.title': 'Orders',
  'orders.new_order': 'New Order',
  'orders.order_number': 'Order Number',
  'orders.status': 'Status',
  'orders.customer': 'Customer',
  'orders.amount': 'Amount',
  'orders.date': 'Date',
  'orders.product': 'Product',
  'orders.quantity': 'Quantity',
  'orders.price': 'Price',
  'orders.total': 'Total',
  'orders.pending': 'Pending',
  'orders.processing': 'Processing',
  'orders.completed': 'Completed',
  'orders.cancelled': 'Cancelled',
  'orders.paid': 'Paid',
  'orders.unpaid': 'Unpaid',
  'orders.view_order': 'View Order',
  'orders.track_order': 'Track Order',
  'orders.order_details': 'Order Details',
  'orders.customer_info': 'Customer Information',
  'orders.shipping_address': 'Shipping Address',
  'orders.payment_status': 'Payment Status',
  'orders.order_history': 'Order History',
  'orders.no_orders': 'No orders found',
  'orders.place_order': 'Place Order',
  'orders.order_placed': 'Order Placed Successfully',
  'orders.pending_payment': 'Pending Payment',
  'orders.paid_by_user': 'Paid by User',
  'orders.postpaid_pending': 'Postpaid Pending',
  'orders.order_id': 'Order ID',
  'orders.customer_name': 'Customer Name',
  'orders.customer_phone': 'Customer Phone',
  'orders.customer_email': 'Customer Email',
  'orders.shipping_info': 'Shipping Information',
  'orders.city': 'City',
  'orders.state': 'State',
  'orders.pincode': 'Pincode',
  'orders.country': 'Country',
  'orders.notes': 'Notes',
  'orders.seller_notes': 'Seller Notes',
  'orders.admin_notes': 'Admin Notes',
  'orders.tracking_number': 'Tracking Number',
  'orders.courier': 'Courier',
  'orders.estimated_delivery': 'Estimated Delivery',
  'orders.delivered': 'Delivered',
  'orders.shipped': 'Shipped',
  'orders.out_for_delivery': 'Out for Delivery',
  'orders.returned': 'Returned',
  'orders.refunded': 'Refunded',
  'orders.disputed': 'Disputed',
  'orders.on_hold': 'On Hold',
  'orders.order_cancelled': 'Order Cancelled',
  'orders.order_completed': 'Order Completed',
  'orders.chat_with_support': 'Chat with Support',
  'orders.bulk_order': 'Bulk Order',
  'orders.create_order': 'Create Order',
  'orders.update_status': 'Update Status',
  'orders.export_orders': 'Export Orders',
  'orders.filter_orders': 'Filter Orders',
  'orders.search_orders': 'Search orders...',
  
  // Payments
  'payments.title': 'Payments',
  'payments.request_payout': 'Request Payout',
  'payments.add_funds': 'Add Funds',
  'payments.transaction_history': 'Transaction History',
  'payments.balance': 'Balance',
  'payments.available': 'Available',
  'payments.pending': 'Pending',
  'payments.payout_method': 'Payout Method',
  'payments.bank_transfer': 'Bank Transfer',
  'payments.upi': 'UPI',
  'payments.crypto': 'Cryptocurrency',
  'payments.amount': 'Amount',
  'payments.fee': 'Fee',
  'payments.net_amount': 'Net Amount',
  'payments.request_date': 'Request Date',
  'payments.processed_date': 'Processed Date',
  'payments.status': 'Status',
  'payments.approved': 'Approved',
  'payments.rejected': 'Rejected',
  'payments.processing': 'Processing',
  'payments.completed': 'Completed',
  'payments.no_transactions': 'No transactions found',
  'payments.minimum_payout': 'Minimum Payout',
  'payments.payment_details': 'Payment Details',
  'payments.bank_name': 'Bank Name',
  'payments.account_number': 'Account Number',
  'payments.ifsc_code': 'IFSC Code',
  'payments.account_holder': 'Account Holder Name',
  'payments.upi_id': 'UPI ID',
  'payments.wallet_address': 'Wallet Address',
  'payments.commission_earned': 'Commission Earned',
  'payments.payout_history': 'Payout History',
  'payments.payout_request_submitted': 'Payout request submitted',
  'payments.insufficient_balance': 'Insufficient balance',
  'payments.select_method': 'Select Payment Method',
  'payments.enter_amount': 'Enter Amount',
  'payments.confirm_payout': 'Confirm Payout',
  'payments.payout_successful': 'Payout Successful',
  'payments.payout_failed': 'Payout Failed',
  'payments.transaction_type': 'Transaction Type',
  'payments.credit': 'Credit',
  'payments.debit': 'Debit',
  'payments.order_payment': 'Order Payment',
  'payments.wallet_topup': 'Wallet Top-up',
  'payments.refund': 'Refund',
  'payments.bonus': 'Bonus',
  'payments.adjustment': 'Adjustment',
  'payments.paypal': 'PayPal',
  'payments.usdt': 'USDT (Tether)',
  'payments.bitcoin': 'Bitcoin',
  'payments.ethereum': 'Ethereum',
  
  // Products
  'products.title': 'Products',
  'products.browse': 'Browse Products',
  'products.add_to_store': 'Add to Store',
  'products.remove_from_store': 'Remove from Store',
  'products.price': 'Price',
  'products.base_price': 'Base Price',
  'products.selling_price': 'Selling Price',
  'products.profit_margin': 'Profit Margin',
  'products.stock': 'Stock',
  'products.in_stock': 'In Stock',
  'products.out_of_stock': 'Out of Stock',
  'products.category': 'Category',
  'products.description': 'Description',
  'products.sku': 'SKU',
  'products.no_products': 'No products found',
  'products.search_products': 'Search products...',
  'products.my_products': 'My Products',
  'products.all_products': 'All Products',
  'products.add_product': 'Add Product',
  'products.edit_product': 'Edit Product',
  'products.delete_product': 'Delete Product',
  'products.product_name': 'Product Name',
  'products.product_image': 'Product Image',
  'products.product_gallery': 'Product Gallery',
  'products.weight': 'Weight',
  'products.dimensions': 'Dimensions',
  'products.tags': 'Tags',
  'products.variants': 'Variants',
  'products.reviews': 'Reviews',
  'products.rating': 'Rating',
  'products.featured': 'Featured',
  'products.new_arrival': 'New Arrival',
  'products.best_seller': 'Best Seller',
  'products.low_stock': 'Low Stock',
  'products.set_custom_price': 'Set Custom Price',
  'products.import_products': 'Import Products',
  'products.export_products': 'Export Products',
  
  // Storefront
  'storefront.title': 'My Storefront',
  'storefront.setup': 'Setup Storefront',
  'storefront.name': 'Store Name',
  'storefront.slug': 'Store URL',
  'storefront.banner': 'Store Banner',
  'storefront.products': 'Store Products',
  'storefront.share': 'Share Store',
  'storefront.copy_link': 'Copy Link',
  'storefront.preview': 'Preview Store',
  'storefront.settings': 'Store Settings',
  'storefront.description': 'Store Description',
  'storefront.logo': 'Store Logo',
  'storefront.theme': 'Store Theme',
  'storefront.social_links': 'Social Links',
  'storefront.contact_info': 'Contact Information',
  'storefront.about': 'About Store',
  'storefront.policies': 'Store Policies',
  'storefront.return_policy': 'Return Policy',
  'storefront.shipping_policy': 'Shipping Policy',
  'storefront.add_to_cart': 'Add to Cart',
  'storefront.buy_now': 'Buy Now',
  'storefront.checkout': 'Checkout',
  'storefront.cart': 'Cart',
  'storefront.empty_cart': 'Your cart is empty',
  'storefront.continue_shopping': 'Continue Shopping',
  'storefront.proceed_to_checkout': 'Proceed to Checkout',
  'storefront.subtotal': 'Subtotal',
  'storefront.shipping': 'Shipping',
  'storefront.tax': 'Tax',
  'storefront.discount': 'Discount',
  'storefront.grand_total': 'Grand Total',
  'storefront.apply_coupon': 'Apply Coupon',
  'storefront.coupon_code': 'Coupon Code',
  'storefront.featured_products': 'Featured Products',
  'storefront.new_arrivals': 'New Arrivals',
  'storefront.categories': 'Categories',
  
  // Support
  'support.title': 'Support',
  'support.chat': 'Live Chat',
  'support.tickets': 'Support Tickets',
  'support.faq': 'FAQ',
  'support.contact': 'Contact Us',
  'support.new_ticket': 'New Ticket',
  'support.ticket_status': 'Ticket Status',
  'support.open': 'Open',
  'support.closed': 'Closed',
  'support.in_progress': 'In Progress',
  'support.raise_ticket': 'Raise a Ticket',
  'support.ticket_id': 'Ticket ID',
  'support.subject': 'Subject',
  'support.message': 'Message',
  'support.priority': 'Priority',
  'support.low': 'Low',
  'support.medium': 'Medium',
  'support.high': 'High',
  'support.urgent': 'Urgent',
  'support.response': 'Response',
  'support.awaiting_response': 'Awaiting Response',
  'support.resolved': 'Resolved',
  'support.ticket_created': 'Ticket created successfully',
  'support.chat_support': 'Chat with Support',
  'support.email_support': 'Email Support',
  'support.phone_support': 'Phone Support',
  'support.working_hours': 'Working Hours',
  'support.response_time': 'Average Response Time',
  'support.type_message': 'Type your message...',
  'support.send': 'Send',
  'support.online': 'Online',
  'support.offline': 'Offline',
  'support.typing': 'typing...',
  
  // Settings
  'settings.title': 'Settings',
  'settings.general': 'General',
  'settings.security': 'Security',
  'settings.notifications': 'Notifications',
  'settings.payment': 'Payment Settings',
  'settings.save_changes': 'Save Changes',
  'settings.account': 'Account',
  'settings.privacy': 'Privacy',
  'settings.preferences': 'Preferences',
  'settings.email_notifications': 'Email Notifications',
  'settings.push_notifications': 'Push Notifications',
  'settings.sms_notifications': 'SMS Notifications',
  'settings.order_updates': 'Order Updates',
  'settings.payment_alerts': 'Payment Alerts',
  'settings.promotional': 'Promotional Messages',
  'settings.newsletter': 'Newsletter',
  'settings.two_factor_auth': 'Two-Factor Authentication',
  'settings.session_management': 'Session Management',
  'settings.active_sessions': 'Active Sessions',
  'settings.logout_all': 'Logout All Devices',
  'settings.delete_account': 'Delete Account',
  'settings.export_data': 'Export My Data',
  
  // Landing Page
  'landing.hero_title': 'Start Your Dropshipping Business',
  'landing.hero_subtitle': 'The modern dropshipping platform. Empower your dropshippers. Grow together.',
  'landing.get_started': 'Get Started Free',
  'landing.watch_demo': 'Watch Demo',
  'landing.track_order': 'Track Order',
  'landing.sign_in': 'Sign In',
  'landing.features': 'Features',
  'landing.how_it_works': 'How It Works',
  'landing.testimonials': 'Testimonials',
  'landing.faq': 'FAQ',
  'landing.contact': 'Contact',
  'landing.pricing': 'Pricing',
  'landing.about_us': 'About Us',
  'landing.terms': 'Terms of Service',
  'landing.privacy': 'Privacy Policy',
  'landing.copyright': 'All rights reserved',
  'landing.trusted_by': 'Trusted by thousands of dropshippers',
  'landing.easy_setup': 'Easy Setup',
  'landing.secure_payments': 'Secure Payments',
  'landing.fast_shipping': 'Fast Shipping',
  'landing.support_24_7': '24/7 Support',
  'landing.start_selling': 'Start Selling Today',
  'landing.join_now': 'Join Now',
  'landing.learn_more': 'Learn More',
  
  // Activity Log
  'activity.login': 'Login',
  'activity.logout': 'Logout',
  'activity.order_placed': 'Order Placed',
  'activity.payout_request': 'Payout Request',
  'activity.profile_update': 'Profile Update',
  'activity.postpaid_repayment': 'Postpaid Repayment',
  'activity.crypto_payment': 'Crypto Payment',
  'activity.payment_details_update': 'Payment Details Update',
  'activity.kyc_submission': 'KYC Submission',
  'activity.current_session': 'Current Session',
  'activity.no_activity': 'No activity logs found',
  'activity.history_will_appear': 'Your login history will appear here',
  'activity.password_change': 'Password Changed',
  'activity.settings_update': 'Settings Updated',
  'activity.storefront_update': 'Storefront Updated',
  'activity.product_added': 'Product Added',
  'activity.product_removed': 'Product Removed',
  'activity.order_cancelled': 'Order Cancelled',
  'activity.ticket_created': 'Support Ticket Created',
  'activity.proof_submitted': 'Proof Submitted',
  
  // Workspace
  'workspace.title': 'Workspace',
  'workspace.submit_proof': 'Submit Proof',
  'workspace.my_proofs': 'My Proofs',
  'workspace.analytics': 'Analytics',
  'workspace.work_type': 'Work Type',
  'workspace.proof_link': 'Proof Link',
  'workspace.notes': 'Notes',
  'workspace.upload_images': 'Upload Images',
  'workspace.submit': 'Submit Proof',
  'workspace.pending_review': 'Pending Review',
  'workspace.approved': 'Approved',
  'workspace.rejected': 'Rejected',
  'workspace.admin_remark': 'Admin Remark',
  'workspace.submission_date': 'Submission Date',
  'workspace.review_queue': 'Review Queue',
  'workspace.history': 'History',
  'workspace.proof_images': 'Proof Images',
  'workspace.no_proofs': 'No proofs submitted yet',
  'workspace.total_submissions': 'Total Submissions',
  'workspace.approval_rate': 'Approval Rate',
  
  // KYC
  'kyc.title': 'KYC Verification',
  'kyc.description': 'Complete your identity verification to unlock all features',
  'kyc.status': 'KYC Status',
  'kyc.pending': 'Pending Verification',
  'kyc.verified': 'Verified',
  'kyc.rejected': 'Verification Failed',
  'kyc.not_submitted': 'Not Submitted',
  'kyc.submit': 'Submit for Verification',
  'kyc.document_type': 'Document Type',
  'kyc.id_card': 'ID Card',
  'kyc.passport': 'Passport',
  'kyc.driving_license': 'Driving License',
  'kyc.voter_id': 'Voter ID',
  'kyc.aadhaar': 'Aadhaar Card',
  'kyc.pan_card': 'PAN Card',
  'kyc.front_image': 'Document Front',
  'kyc.back_image': 'Document Back',
  'kyc.selfie': 'Selfie with Document',
  'kyc.full_name': 'Full Name (as on document)',
  'kyc.document_number': 'Document Number',
  'kyc.date_of_birth': 'Date of Birth',
  'kyc.under_review': 'Your documents are under review',
  'kyc.verification_success': 'Verification completed successfully',
  'kyc.verification_failed': 'Verification failed. Please resubmit.',
  
  // Wallet
  'wallet.title': 'Wallet',
  'wallet.balance': 'Current Balance',
  'wallet.add_money': 'Add Money',
  'wallet.withdraw': 'Withdraw',
  'wallet.transactions': 'Transactions',
  'wallet.no_transactions': 'No transactions yet',
  'wallet.transfer': 'Transfer',
  'wallet.receive': 'Receive',
  'wallet.send': 'Send',
  'wallet.usd_balance': 'USD Balance',
  'wallet.inr_balance': 'INR Balance',
  
  // Crypto
  'crypto.title': 'Crypto Payments',
  'crypto.submit_payment': 'Submit Payment',
  'crypto.payment_history': 'Payment History',
  'crypto.wallet_address': 'Wallet Address',
  'crypto.transaction_hash': 'Transaction Hash',
  'crypto.network': 'Network',
  'crypto.amount_sent': 'Amount Sent',
  'crypto.verification_pending': 'Verification Pending',
  'crypto.verified': 'Verified',
  'crypto.failed': 'Failed',
  'crypto.copy_address': 'Copy Address',
  'crypto.scan_qr': 'Scan QR Code',
  
  // Help
  'help.title': 'Help & FAQ',
  'help.getting_started': 'Getting Started',
  'help.tutorials': 'Video Tutorials',
  'help.faq': 'Frequently Asked Questions',
  'help.contact_support': 'Contact Support',
  'help.documentation': 'Documentation',
  'help.guides': 'Guides',
  'help.video_tutorials': 'Video Tutorials',
  'help.watch': 'Watch',
  'help.watched': 'Watched',
  'help.progress': 'Progress',
  
  // Notifications
  'notifications.title': 'Notifications',
  'notifications.all': 'All',
  'notifications.unread': 'Unread',
  'notifications.mark_read': 'Mark as Read',
  'notifications.mark_all_read': 'Mark All as Read',
  'notifications.clear_all': 'Clear All',
  'notifications.no_notifications': 'No notifications',
  'notifications.new': 'New',
  
  // Errors
  'error.generic': 'Something went wrong',
  'error.network': 'Network error. Please try again.',
  'error.unauthorized': 'Unauthorized access',
  'error.not_found': 'Not found',
  'error.try_again': 'Try Again',
  'error.invalid_input': 'Invalid input',
  'error.required_field': 'This field is required',
  'error.invalid_email': 'Invalid email address',
  'error.password_mismatch': 'Passwords do not match',
  'error.password_too_short': 'Password must be at least 8 characters',
  'error.file_too_large': 'File is too large',
  'error.invalid_file_type': 'Invalid file type',
  'error.upload_failed': 'Upload failed',
  'error.server_error': 'Server error. Please try again later.',
  'error.session_expired': 'Session expired. Please login again.',
  'error.permission_denied': 'Permission denied',
  'error.rate_limited': 'Too many requests. Please wait.',
  'error.maintenance': 'System is under maintenance',
  
  // Time
  'time.just_now': 'Just now',
  'time.minutes_ago': 'minutes ago',
  'time.hours_ago': 'hours ago',
  'time.days_ago': 'days ago',
  'time.yesterday': 'Yesterday',
  'time.today': 'Today',
  'time.tomorrow': 'Tomorrow',
  'time.this_week': 'This week',
  'time.last_week': 'Last week',
  'time.this_month': 'This month',
  'time.last_month': 'Last month',
  
  // Confirmation
  'confirm.delete': 'Are you sure you want to delete this?',
  'confirm.cancel_order': 'Are you sure you want to cancel this order?',
  'confirm.logout': 'Are you sure you want to logout?',
  'confirm.remove': 'Are you sure you want to remove this?',
  'confirm.submit': 'Are you sure you want to submit?',
  'confirm.action_irreversible': 'This action cannot be undone.',
  
  // Misc
  'misc.or': 'or',
  'misc.and': 'and',
  'misc.with': 'with',
  'misc.by': 'by',
  'misc.for': 'for',
  'misc.in': 'in',
  'misc.items': 'items',
  'misc.results': 'results',
  'misc.page': 'Page',
  'misc.of': 'of',
  'misc.showing': 'Showing',
  'misc.per_page': 'per page',
  'misc.sort_by': 'Sort by',
  'misc.order_by': 'Order by',
  'misc.ascending': 'Ascending',
  'misc.descending': 'Descending',
  'misc.newest': 'Newest',
  'misc.oldest': 'Oldest',
  'misc.popular': 'Popular',
  'misc.recent': 'Recent',
};

// Hindi translations
const hiTranslations: Record<string, string> = {
  // Common
  'common.loading': 'लोड हो रहा है...',
  'common.save': 'सहेजें',
  'common.cancel': 'रद्द करें',
  'common.delete': 'हटाएं',
  'common.edit': 'संपादित करें',
  'common.submit': 'जमा करें',
  'common.confirm': 'पुष्टि करें',
  'common.back': 'वापस',
  'common.next': 'अगला',
  'common.search': 'खोजें',
  'common.filter': 'फ़िल्टर',
  'common.refresh': 'रीफ्रेश',
  'common.close': 'बंद करें',
  'common.view': 'देखें',
  'common.download': 'डाउनलोड',
  'common.upload': 'अपलोड',
  'common.yes': 'हाँ',
  'common.no': 'नहीं',
  'common.actions': 'क्रियाएं',
  'common.status': 'स्थिति',
  'common.date': 'दिनांक',
  'common.amount': 'राशि',
  'common.total': 'कुल',
  'common.details': 'विवरण',
  'common.success': 'सफल',
  'common.error': 'त्रुटि',
  'common.warning': 'चेतावनी',
  'common.info': 'जानकारी',
  'common.all': 'सभी',
  'common.none': 'कोई नहीं',
  'common.select': 'चुनें',
  'common.clear': 'साफ़ करें',
  'common.apply': 'लागू करें',
  'common.reset': 'रीसेट करें',
  'common.update': 'अपडेट करें',
  'common.create': 'बनाएं',
  'common.add': 'जोड़ें',
  'common.remove': 'हटाएं',
  'common.copy': 'कॉपी करें',
  'common.share': 'साझा करें',
  'common.export': 'एक्सपोर्ट',
  'common.import': 'इम्पोर्ट',
  'common.print': 'प्रिंट',
  'common.active': 'सक्रिय',
  'common.inactive': 'निष्क्रिय',
  'common.enabled': 'सक्षम',
  'common.disabled': 'अक्षम',
  'common.pending': 'लंबित',
  'common.approved': 'स्वीकृत',
  'common.rejected': 'अस्वीकृत',
  'common.completed': 'पूर्ण',
  'common.failed': 'विफल',
  'common.processing': 'प्रोसेसिंग',
  'common.from': 'से',
  'common.to': 'तक',
  'common.copied': 'कॉपी हो गया!',
  'common.saved': 'सहेजा गया!',
  'common.updated': 'अपडेट हो गया!',
  'common.deleted': 'हटा दिया गया!',
  'common.created': 'बनाया गया!',
  
  // Navigation
  'nav.dashboard': 'डैशबोर्ड',
  'nav.profile': 'प्रोफ़ाइल',
  'nav.storefront': 'मेरी दुकान',
  'nav.products': 'उत्पाद ब्राउज़ करें',
  'nav.orders': 'आदेश',
  'nav.payments': 'भुगतान',
  'nav.workspace': 'कार्यस्थान',
  'nav.support': 'सहायता',
  'nav.help': 'मदद और FAQ',
  'nav.logout': 'लॉग आउट',
  'nav.settings': 'सेटिंग्स',
  'nav.home': 'होम',
  'nav.chat': 'चैट',
  'nav.notifications': 'सूचनाएं',
  'nav.kyc': 'केवाईसी सत्यापन',
  'nav.wallet': 'वॉलेट',
  'nav.crypto': 'क्रिप्टो भुगतान',
  'nav.ai': 'AI सहायक',
  'nav.admin': 'एडमिन पैनल',
  'nav.users': 'उपयोगकर्ता',
  'nav.reports': 'रिपोर्ट',
  'nav.payouts': 'भुगतान',
  
  // Profile
  'profile.title': 'मेरी प्रोफ़ाइल',
  'profile.description': 'अपनी प्रोफ़ाइल जानकारी, सुरक्षा सेटिंग्स और गतिविधि देखें।',
  'profile.appearance': 'दिखावट',
  'profile.appearance_desc': 'डैशबोर्ड के लिए अपनी पसंदीदा थीम चुनें',
  'profile.language': 'भाषा',
  'profile.language_desc': 'अपनी पसंदीदा भाषा चुनें',
  'profile.security': 'सुरक्षा',
  'profile.change_password': 'पासवर्ड बदलें',
  'profile.two_factor': 'दो-कारक प्रमाणीकरण',
  'profile.login_activity': 'लॉगिन गतिविधि',
  'profile.account_info': 'खाता जानकारी',
  'profile.email': 'ईमेल',
  'profile.name': 'नाम',
  'profile.phone': 'फ़ोन',
  'profile.address': 'पता',
  'profile.update_profile': 'प्रोफ़ाइल अपडेट करें',
  'profile.profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई',
  'profile.avatar': 'प्रोफ़ाइल चित्र',
  'profile.bio': 'बायो',
  'profile.joined': 'सदस्य बने',
  'profile.level': 'स्तर',
  'profile.referral_code': 'रेफरल कोड',
  
  // Auth
  'auth.login': 'लॉग इन',
  'auth.signup': 'साइन अप',
  'auth.email': 'ईमेल',
  'auth.password': 'पासवर्ड',
  'auth.forgot_password': 'पासवर्ड भूल गए?',
  'auth.remember_me': 'मुझे याद रखें',
  'auth.welcome_back': 'वापसी पर स्वागत है',
  'auth.sign_in_desc': 'अपने डैशबोर्ड तक पहुंचने के लिए साइन इन करें',
  'auth.email_address': 'ईमेल पता',
  'auth.create_account': 'खाता बनाएं',
  'auth.already_have_account': 'पहले से खाता है?',
  'auth.dont_have_account': 'खाता नहीं है?',
  'auth.verify_email': 'ईमेल सत्यापित करें',
  'auth.resend_code': 'कोड पुनः भेजें',
  'auth.verification_code': 'सत्यापन कोड',
  'auth.new_password': 'नया पासवर्ड',
  'auth.confirm_password': 'पासवर्ड की पुष्टि करें',
  'auth.reset_password': 'पासवर्ड रीसेट करें',
  'auth.password_changed': 'पासवर्ड सफलतापूर्वक बदल गया',
  'auth.invalid_credentials': 'अमान्य ईमेल या पासवर्ड',
  'auth.account_created': 'खाता सफलतापूर्वक बनाया गया',
  'auth.logout_success': 'सफलतापूर्वक लॉग आउट हो गया',
  'auth.session_expired': 'सत्र समाप्त हो गया। कृपया फिर से लॉगिन करें।',
  
  // Dashboard
  'dashboard.welcome': 'वापसी पर स्वागत है',
  'dashboard.total_orders': 'कुल आदेश',
  'dashboard.pending_orders': 'लंबित आदेश',
  'dashboard.wallet_balance': 'वॉलेट बैलेंस',
  'dashboard.total_earnings': 'कुल कमाई',
  'dashboard.recent_orders': 'हाल के आदेश',
  'dashboard.quick_actions': 'त्वरित क्रियाएं',
  'dashboard.view_all': 'सभी देखें',
  'dashboard.todays_sales': 'आज की बिक्री',
  'dashboard.this_week': 'इस सप्ताह',
  'dashboard.this_month': 'इस महीने',
  'dashboard.growth': 'वृद्धि',
  'dashboard.revenue': 'राजस्व',
  'dashboard.profit': 'लाभ',
  'dashboard.commission': 'कमीशन',
  'dashboard.store_performance': 'स्टोर प्रदर्शन',
  'dashboard.order_analytics': 'ऑर्डर एनालिटिक्स',
  'dashboard.getting_started': 'शुरू करें',
  'dashboard.watch_tutorial': 'ट्यूटोरियल देखें',
  'dashboard.completed_orders': 'पूर्ण आदेश',
  'dashboard.cancelled_orders': 'रद्द आदेश',
  'dashboard.average_order_value': 'औसत ऑर्डर मूल्य',
  'dashboard.postpaid_credit': 'पोस्टपेड क्रेडिट',
  'dashboard.available_credit': 'उपलब्ध क्रेडिट',
  'dashboard.used_credit': 'उपयोग किया गया क्रेडिट',
  'dashboard.due_amount': 'बकाया राशि',
  
  // Orders
  'orders.title': 'आदेश',
  'orders.new_order': 'नया आदेश',
  'orders.order_number': 'आदेश संख्या',
  'orders.status': 'स्थिति',
  'orders.customer': 'ग्राहक',
  'orders.amount': 'राशि',
  'orders.date': 'दिनांक',
  'orders.product': 'उत्पाद',
  'orders.quantity': 'मात्रा',
  'orders.price': 'मूल्य',
  'orders.total': 'कुल',
  'orders.pending': 'लंबित',
  'orders.processing': 'प्रोसेसिंग',
  'orders.completed': 'पूर्ण',
  'orders.cancelled': 'रद्द',
  'orders.paid': 'भुगतान हो गया',
  'orders.unpaid': 'अवैतनिक',
  'orders.view_order': 'आदेश देखें',
  'orders.track_order': 'आदेश ट्रैक करें',
  'orders.order_details': 'आदेश विवरण',
  'orders.customer_info': 'ग्राहक जानकारी',
  'orders.shipping_address': 'शिपिंग पता',
  'orders.payment_status': 'भुगतान स्थिति',
  'orders.order_history': 'आदेश इतिहास',
  'orders.no_orders': 'कोई आदेश नहीं मिला',
  'orders.place_order': 'आदेश दें',
  'orders.order_placed': 'आदेश सफलतापूर्वक दिया गया',
  'orders.pending_payment': 'भुगतान लंबित',
  'orders.paid_by_user': 'उपयोगकर्ता द्वारा भुगतान',
  'orders.postpaid_pending': 'पोस्टपेड लंबित',
  'orders.order_id': 'ऑर्डर आईडी',
  'orders.customer_name': 'ग्राहक का नाम',
  'orders.customer_phone': 'ग्राहक का फ़ोन',
  'orders.customer_email': 'ग्राहक का ईमेल',
  'orders.shipping_info': 'शिपिंग जानकारी',
  'orders.city': 'शहर',
  'orders.state': 'राज्य',
  'orders.pincode': 'पिनकोड',
  'orders.country': 'देश',
  'orders.notes': 'नोट्स',
  'orders.tracking_number': 'ट्रैकिंग नंबर',
  'orders.courier': 'कूरियर',
  'orders.delivered': 'डिलीवर हो गया',
  'orders.shipped': 'शिप हो गया',
  'orders.returned': 'वापस',
  'orders.refunded': 'वापसी हो गई',
  'orders.create_order': 'आदेश बनाएं',
  'orders.update_status': 'स्थिति अपडेट करें',
  'orders.search_orders': 'आदेश खोजें...',
  
  // Payments
  'payments.title': 'भुगतान',
  'payments.request_payout': 'भुगतान का अनुरोध करें',
  'payments.add_funds': 'फंड जोड़ें',
  'payments.transaction_history': 'लेन-देन इतिहास',
  'payments.balance': 'बैलेंस',
  'payments.available': 'उपलब्ध',
  'payments.pending': 'लंबित',
  'payments.payout_method': 'भुगतान विधि',
  'payments.bank_transfer': 'बैंक ट्रांसफर',
  'payments.upi': 'यूपीआई',
  'payments.crypto': 'क्रिप्टोकरेंसी',
  'payments.amount': 'राशि',
  'payments.fee': 'शुल्क',
  'payments.net_amount': 'शुद्ध राशि',
  'payments.request_date': 'अनुरोध तिथि',
  'payments.processed_date': 'प्रोसेस तिथि',
  'payments.status': 'स्थिति',
  'payments.approved': 'स्वीकृत',
  'payments.rejected': 'अस्वीकृत',
  'payments.processing': 'प्रोसेसिंग',
  'payments.completed': 'पूर्ण',
  'payments.no_transactions': 'कोई लेन-देन नहीं मिला',
  'payments.minimum_payout': 'न्यूनतम भुगतान',
  'payments.payment_details': 'भुगतान विवरण',
  'payments.bank_name': 'बैंक का नाम',
  'payments.account_number': 'खाता संख्या',
  'payments.ifsc_code': 'आईएफएससी कोड',
  'payments.account_holder': 'खाता धारक का नाम',
  'payments.upi_id': 'यूपीआई आईडी',
  'payments.wallet_address': 'वॉलेट पता',
  'payments.commission_earned': 'कमीशन अर्जित',
  'payments.payout_history': 'भुगतान इतिहास',
  'payments.payout_request_submitted': 'भुगतान अनुरोध जमा किया गया',
  'payments.insufficient_balance': 'अपर्याप्त बैलेंस',
  'payments.select_method': 'भुगतान विधि चुनें',
  'payments.enter_amount': 'राशि दर्ज करें',
  'payments.confirm_payout': 'भुगतान की पुष्टि करें',
  'payments.credit': 'क्रेडिट',
  'payments.debit': 'डेबिट',
  'payments.order_payment': 'ऑर्डर भुगतान',
  'payments.wallet_topup': 'वॉलेट टॉप-अप',
  'payments.refund': 'वापसी',
  'payments.bonus': 'बोनस',
  
  // Products
  'products.title': 'उत्पाद',
  'products.browse': 'उत्पाद ब्राउज़ करें',
  'products.add_to_store': 'स्टोर में जोड़ें',
  'products.remove_from_store': 'स्टोर से हटाएं',
  'products.price': 'मूल्य',
  'products.base_price': 'बेस प्राइस',
  'products.selling_price': 'विक्रय मूल्य',
  'products.profit_margin': 'लाभ मार्जिन',
  'products.stock': 'स्टॉक',
  'products.in_stock': 'स्टॉक में',
  'products.out_of_stock': 'स्टॉक में नहीं',
  'products.category': 'श्रेणी',
  'products.description': 'विवरण',
  'products.sku': 'एसकेयू',
  'products.no_products': 'कोई उत्पाद नहीं मिला',
  'products.search_products': 'उत्पाद खोजें...',
  'products.my_products': 'मेरे उत्पाद',
  'products.all_products': 'सभी उत्पाद',
  'products.add_product': 'उत्पाद जोड़ें',
  'products.edit_product': 'उत्पाद संपादित करें',
  'products.product_name': 'उत्पाद का नाम',
  'products.reviews': 'समीक्षाएं',
  'products.rating': 'रेटिंग',
  'products.featured': 'विशेष',
  'products.best_seller': 'बेस्ट सेलर',
  'products.low_stock': 'कम स्टॉक',
  'products.set_custom_price': 'कस्टम मूल्य सेट करें',
  
  // Storefront
  'storefront.title': 'मेरी दुकान',
  'storefront.setup': 'स्टोरफ्रंट सेटअप',
  'storefront.name': 'स्टोर का नाम',
  'storefront.slug': 'स्टोर URL',
  'storefront.banner': 'स्टोर बैनर',
  'storefront.products': 'स्टोर उत्पाद',
  'storefront.share': 'स्टोर साझा करें',
  'storefront.copy_link': 'लिंक कॉपी करें',
  'storefront.preview': 'स्टोर पूर्वावलोकन',
  'storefront.settings': 'स्टोर सेटिंग्स',
  'storefront.description': 'स्टोर विवरण',
  'storefront.logo': 'स्टोर लोगो',
  'storefront.add_to_cart': 'कार्ट में जोड़ें',
  'storefront.buy_now': 'अभी खरीदें',
  'storefront.checkout': 'चेकआउट',
  'storefront.cart': 'कार्ट',
  'storefront.empty_cart': 'आपका कार्ट खाली है',
  'storefront.continue_shopping': 'शॉपिंग जारी रखें',
  'storefront.proceed_to_checkout': 'चेकआउट पर जाएं',
  'storefront.subtotal': 'उप-योग',
  'storefront.shipping': 'शिपिंग',
  'storefront.tax': 'कर',
  'storefront.discount': 'छूट',
  'storefront.grand_total': 'कुल योग',
  'storefront.apply_coupon': 'कूपन लागू करें',
  'storefront.featured_products': 'विशेष उत्पाद',
  'storefront.categories': 'श्रेणियां',
  
  // Support
  'support.title': 'सहायता',
  'support.chat': 'लाइव चैट',
  'support.tickets': 'सहायता टिकट',
  'support.faq': 'अक्सर पूछे जाने वाले प्रश्न',
  'support.contact': 'संपर्क करें',
  'support.new_ticket': 'नया टिकट',
  'support.ticket_status': 'टिकट स्थिति',
  'support.open': 'खुला',
  'support.closed': 'बंद',
  'support.in_progress': 'प्रगति में',
  'support.raise_ticket': 'टिकट उठाएं',
  'support.ticket_id': 'टिकट आईडी',
  'support.subject': 'विषय',
  'support.message': 'संदेश',
  'support.priority': 'प्राथमिकता',
  'support.low': 'कम',
  'support.medium': 'मध्यम',
  'support.high': 'उच्च',
  'support.urgent': 'तत्काल',
  'support.resolved': 'हल हो गया',
  'support.ticket_created': 'टिकट सफलतापूर्वक बनाया गया',
  'support.type_message': 'अपना संदेश टाइप करें...',
  'support.send': 'भेजें',
  'support.online': 'ऑनलाइन',
  'support.offline': 'ऑफलाइन',
  'support.typing': 'टाइप कर रहा है...',
  
  // Settings
  'settings.title': 'सेटिंग्स',
  'settings.general': 'सामान्य',
  'settings.security': 'सुरक्षा',
  'settings.notifications': 'सूचनाएं',
  'settings.payment': 'भुगतान सेटिंग्स',
  'settings.save_changes': 'परिवर्तन सहेजें',
  'settings.account': 'खाता',
  'settings.privacy': 'गोपनीयता',
  'settings.preferences': 'प्राथमिकताएं',
  'settings.email_notifications': 'ईमेल सूचनाएं',
  'settings.push_notifications': 'पुश सूचनाएं',
  'settings.order_updates': 'ऑर्डर अपडेट',
  'settings.payment_alerts': 'भुगतान अलर्ट',
  
  // Landing Page
  'landing.hero_title': 'अपना ड्रॉपशिपिंग व्यवसाय शुरू करें',
  'landing.hero_subtitle': 'आधुनिक ड्रॉपशिपिंग प्लेटफॉर्म। अपने ड्रॉपशिपर्स को सशक्त बनाएं। साथ मिलकर बढ़ें।',
  'landing.get_started': 'मुफ्त में शुरू करें',
  'landing.watch_demo': 'डेमो देखें',
  'landing.track_order': 'ऑर्डर ट्रैक करें',
  'landing.sign_in': 'साइन इन करें',
  'landing.features': 'विशेषताएं',
  'landing.how_it_works': 'यह कैसे काम करता है',
  'landing.testimonials': 'प्रशंसापत्र',
  'landing.faq': 'अक्सर पूछे जाने वाले प्रश्न',
  'landing.contact': 'संपर्क',
  'landing.pricing': 'मूल्य निर्धारण',
  'landing.about_us': 'हमारे बारे में',
  'landing.terms': 'सेवा की शर्तें',
  'landing.privacy': 'गोपनीयता नीति',
  'landing.copyright': 'सर्वाधिकार सुरक्षित',
  'landing.trusted_by': 'हजारों ड्रॉपशिपर्स द्वारा विश्वसनीय',
  'landing.easy_setup': 'आसान सेटअप',
  'landing.secure_payments': 'सुरक्षित भुगतान',
  'landing.fast_shipping': 'तेज शिपिंग',
  'landing.support_24_7': '24/7 सहायता',
  'landing.start_selling': 'आज ही बिक्री शुरू करें',
  'landing.join_now': 'अभी जुड़ें',
  'landing.learn_more': 'और जानें',
  
  // Activity Log
  'activity.login': 'लॉगिन',
  'activity.logout': 'लॉगआउट',
  'activity.order_placed': 'आदेश दिया गया',
  'activity.payout_request': 'भुगतान अनुरोध',
  'activity.profile_update': 'प्रोफ़ाइल अपडेट',
  'activity.postpaid_repayment': 'पोस्टपेड भुगतान',
  'activity.crypto_payment': 'क्रिप्टो भुगतान',
  'activity.payment_details_update': 'भुगतान विवरण अपडेट',
  'activity.kyc_submission': 'केवाईसी जमा',
  'activity.current_session': 'वर्तमान सत्र',
  'activity.no_activity': 'कोई गतिविधि लॉग नहीं मिला',
  'activity.history_will_appear': 'आपका लॉगिन इतिहास यहां दिखाई देगा',
  'activity.password_change': 'पासवर्ड बदला गया',
  'activity.settings_update': 'सेटिंग्स अपडेट',
  'activity.storefront_update': 'स्टोरफ्रंट अपडेट',
  
  // Workspace
  'workspace.title': 'कार्यस्थान',
  'workspace.submit_proof': 'प्रमाण जमा करें',
  'workspace.my_proofs': 'मेरे प्रमाण',
  'workspace.analytics': 'एनालिटिक्स',
  'workspace.work_type': 'कार्य प्रकार',
  'workspace.proof_link': 'प्रमाण लिंक',
  'workspace.notes': 'नोट्स',
  'workspace.upload_images': 'छवियां अपलोड करें',
  'workspace.submit': 'प्रमाण जमा करें',
  'workspace.pending_review': 'समीक्षा लंबित',
  'workspace.approved': 'स्वीकृत',
  'workspace.rejected': 'अस्वीकृत',
  'workspace.admin_remark': 'एडमिन टिप्पणी',
  'workspace.submission_date': 'जमा तिथि',
  'workspace.review_queue': 'समीक्षा कतार',
  'workspace.history': 'इतिहास',
  'workspace.no_proofs': 'अभी तक कोई प्रमाण नहीं जमा किया गया',
  'workspace.total_submissions': 'कुल सबमिशन',
  'workspace.approval_rate': 'स्वीकृति दर',
  
  // KYC
  'kyc.title': 'केवाईसी सत्यापन',
  'kyc.description': 'सभी सुविधाओं को अनलॉक करने के लिए अपनी पहचान सत्यापित करें',
  'kyc.status': 'केवाईसी स्थिति',
  'kyc.pending': 'सत्यापन लंबित',
  'kyc.verified': 'सत्यापित',
  'kyc.rejected': 'सत्यापन विफल',
  'kyc.not_submitted': 'जमा नहीं किया गया',
  'kyc.submit': 'सत्यापन के लिए जमा करें',
  'kyc.document_type': 'दस्तावेज़ प्रकार',
  'kyc.id_card': 'आईडी कार्ड',
  'kyc.passport': 'पासपोर्ट',
  'kyc.driving_license': 'ड्राइविंग लाइसेंस',
  'kyc.voter_id': 'वोटर आईडी',
  'kyc.aadhaar': 'आधार कार्ड',
  'kyc.pan_card': 'पैन कार्ड',
  'kyc.front_image': 'दस्तावेज़ का अगला भाग',
  'kyc.back_image': 'दस्तावेज़ का पिछला भाग',
  'kyc.selfie': 'दस्तावेज़ के साथ सेल्फी',
  'kyc.full_name': 'पूरा नाम (दस्तावेज़ के अनुसार)',
  'kyc.document_number': 'दस्तावेज़ संख्या',
  'kyc.date_of_birth': 'जन्म तिथि',
  'kyc.under_review': 'आपके दस्तावेज़ समीक्षाधीन हैं',
  
  // Wallet
  'wallet.title': 'वॉलेट',
  'wallet.balance': 'वर्तमान बैलेंस',
  'wallet.add_money': 'पैसे जोड़ें',
  'wallet.withdraw': 'निकालें',
  'wallet.transactions': 'लेन-देन',
  'wallet.no_transactions': 'अभी तक कोई लेन-देन नहीं',
  
  // Crypto
  'crypto.title': 'क्रिप्टो भुगतान',
  'crypto.submit_payment': 'भुगतान जमा करें',
  'crypto.payment_history': 'भुगतान इतिहास',
  'crypto.wallet_address': 'वॉलेट पता',
  'crypto.transaction_hash': 'लेन-देन हैश',
  'crypto.network': 'नेटवर्क',
  'crypto.amount_sent': 'भेजी गई राशि',
  'crypto.verification_pending': 'सत्यापन लंबित',
  'crypto.verified': 'सत्यापित',
  'crypto.failed': 'विफल',
  'crypto.copy_address': 'पता कॉपी करें',
  'crypto.scan_qr': 'QR कोड स्कैन करें',
  
  // Help
  'help.title': 'मदद और FAQ',
  'help.getting_started': 'शुरू करें',
  'help.tutorials': 'वीडियो ट्यूटोरियल',
  'help.faq': 'अक्सर पूछे जाने वाले प्रश्न',
  'help.contact_support': 'सहायता से संपर्क करें',
  'help.documentation': 'दस्तावेज़',
  'help.guides': 'गाइड',
  'help.video_tutorials': 'वीडियो ट्यूटोरियल',
  'help.watch': 'देखें',
  'help.watched': 'देखा गया',
  'help.progress': 'प्रगति',
  
  // Notifications
  'notifications.title': 'सूचनाएं',
  'notifications.all': 'सभी',
  'notifications.unread': 'अपठित',
  'notifications.mark_read': 'पढ़ा हुआ मार्क करें',
  'notifications.mark_all_read': 'सभी पढ़ा हुआ मार्क करें',
  'notifications.clear_all': 'सभी साफ़ करें',
  'notifications.no_notifications': 'कोई सूचना नहीं',
  'notifications.new': 'नया',
  
  // Errors
  'error.generic': 'कुछ गलत हो गया',
  'error.network': 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
  'error.unauthorized': 'अनधिकृत पहुंच',
  'error.not_found': 'नहीं मिला',
  'error.try_again': 'पुनः प्रयास करें',
  'error.invalid_input': 'अमान्य इनपुट',
  'error.required_field': 'यह फ़ील्ड आवश्यक है',
  'error.invalid_email': 'अमान्य ईमेल पता',
  'error.password_mismatch': 'पासवर्ड मेल नहीं खाते',
  'error.password_too_short': 'पासवर्ड कम से कम 8 अक्षर का होना चाहिए',
  'error.file_too_large': 'फ़ाइल बहुत बड़ी है',
  'error.upload_failed': 'अपलोड विफल',
  'error.server_error': 'सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।',
  
  // Time
  'time.just_now': 'अभी अभी',
  'time.minutes_ago': 'मिनट पहले',
  'time.hours_ago': 'घंटे पहले',
  'time.days_ago': 'दिन पहले',
  'time.yesterday': 'कल',
  'time.today': 'आज',
  'time.this_week': 'इस सप्ताह',
  'time.last_week': 'पिछले सप्ताह',
  'time.this_month': 'इस महीने',
  'time.last_month': 'पिछले महीने',
  
  // Confirmation
  'confirm.delete': 'क्या आप वाकई इसे हटाना चाहते हैं?',
  'confirm.cancel_order': 'क्या आप वाकई इस ऑर्डर को रद्द करना चाहते हैं?',
  'confirm.logout': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
  'confirm.action_irreversible': 'यह क्रिया पूर्ववत नहीं की जा सकती।',
};

// Bengali translations
const bnTranslations: Record<string, string> = {
  'common.loading': 'লোড হচ্ছে...',
  'common.save': 'সংরক্ষণ করুন',
  'common.cancel': 'বাতিল করুন',
  'common.delete': 'মুছুন',
  'common.edit': 'সম্পাদনা করুন',
  'common.submit': 'জমা দিন',
  'common.confirm': 'নিশ্চিত করুন',
  'common.back': 'পিছনে',
  'common.next': 'পরবর্তী',
  'common.search': 'খুঁজুন',
  'common.filter': 'ফিল্টার',
  'common.refresh': 'রিফ্রেশ',
  'common.close': 'বন্ধ করুন',
  'common.view': 'দেখুন',
  'common.download': 'ডাউনলোড',
  'common.upload': 'আপলোড',
  'common.yes': 'হ্যাঁ',
  'common.no': 'না',
  'common.status': 'অবস্থা',
  'common.date': 'তারিখ',
  'common.amount': 'পরিমাণ',
  'common.total': 'মোট',
  'common.details': 'বিবরণ',
  'common.success': 'সফল',
  'common.error': 'ত্রুটি',
  'common.warning': 'সতর্কতা',
  'common.all': 'সব',
  'common.pending': 'মুলতুবি',
  'common.approved': 'অনুমোদিত',
  'common.rejected': 'প্রত্যাখ্যাত',
  'common.completed': 'সম্পন্ন',
  'common.copied': 'কপি হয়েছে!',
  
  'nav.dashboard': 'ড্যাশবোর্ড',
  'nav.profile': 'প্রোফাইল',
  'nav.storefront': 'আমার স্টোর',
  'nav.products': 'পণ্য ব্রাউজ করুন',
  'nav.orders': 'অর্ডার',
  'nav.payments': 'পেমেন্ট',
  'nav.workspace': 'কর্মক্ষেত্র',
  'nav.support': 'সাপোর্ট',
  'nav.help': 'সাহায্য ও FAQ',
  'nav.logout': 'লগ আউট',
  'nav.settings': 'সেটিংস',
  'nav.home': 'হোম',
  'nav.chat': 'চ্যাট',
  'nav.notifications': 'নোটিফিকেশন',
  'nav.kyc': 'কেওয়াইসি যাচাই',
  'nav.wallet': 'ওয়ালেট',
  
  'profile.title': 'আমার প্রোফাইল',
  'profile.description': 'আপনার প্রোফাইল তথ্য, নিরাপত্তা সেটিংস এবং কার্যকলাপ দেখুন।',
  'profile.appearance': 'চেহারা',
  'profile.appearance_desc': 'ড্যাশবোর্ডের জন্য আপনার পছন্দের থিম বেছে নিন',
  'profile.language': 'ভাষা',
  'profile.language_desc': 'আপনার পছন্দের ভাষা নির্বাচন করুন',
  'profile.security': 'নিরাপত্তা',
  'profile.change_password': 'পাসওয়ার্ড পরিবর্তন করুন',
  'profile.login_activity': 'লগইন কার্যকলাপ',
  'profile.email': 'ইমেইল',
  'profile.name': 'নাম',
  'profile.phone': 'ফোন',
  'profile.address': 'ঠিকানা',
  
  'auth.login': 'লগ ইন',
  'auth.signup': 'সাইন আপ',
  'auth.email': 'ইমেইল',
  'auth.password': 'পাসওয়ার্ড',
  'auth.forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
  'auth.welcome_back': 'আবার স্বাগতম',
  'auth.sign_in_desc': 'আপনার ড্যাশবোর্ডে প্রবেশ করতে সাইন ইন করুন',
  'auth.create_account': 'অ্যাকাউন্ট তৈরি করুন',
  
  'dashboard.welcome': 'আবার স্বাগতম',
  'dashboard.total_orders': 'মোট অর্ডার',
  'dashboard.pending_orders': 'মুলতুবি অর্ডার',
  'dashboard.wallet_balance': 'ওয়ালেট ব্যালেন্স',
  'dashboard.total_earnings': 'মোট আয়',
  'dashboard.recent_orders': 'সাম্প্রতিক অর্ডার',
  'dashboard.view_all': 'সব দেখুন',
  'dashboard.revenue': 'রাজস্ব',
  'dashboard.profit': 'লাভ',
  'dashboard.commission': 'কমিশন',
  
  'orders.title': 'অর্ডার',
  'orders.new_order': 'নতুন অর্ডার',
  'orders.order_number': 'অর্ডার নম্বর',
  'orders.status': 'অবস্থা',
  'orders.customer': 'গ্রাহক',
  'orders.product': 'পণ্য',
  'orders.quantity': 'পরিমাণ',
  'orders.price': 'দাম',
  'orders.total': 'মোট',
  'orders.pending': 'মুলতুবি',
  'orders.completed': 'সম্পন্ন',
  'orders.cancelled': 'বাতিল',
  'orders.no_orders': 'কোন অর্ডার পাওয়া যায়নি',
  'orders.place_order': 'অর্ডার দিন',
  
  'payments.title': 'পেমেন্ট',
  'payments.request_payout': 'পেআউট অনুরোধ করুন',
  'payments.add_funds': 'টাকা যোগ করুন',
  'payments.transaction_history': 'লেনদেনের ইতিহাস',
  'payments.balance': 'ব্যালেন্স',
  'payments.bank_transfer': 'ব্যাংক ট্রান্সফার',
  'payments.upi': 'ইউপিআই',
  'payments.no_transactions': 'কোন লেনদেন পাওয়া যায়নি',
  
  'products.title': 'পণ্য',
  'products.browse': 'পণ্য ব্রাউজ করুন',
  'products.add_to_store': 'স্টোরে যোগ করুন',
  'products.price': 'দাম',
  'products.stock': 'স্টক',
  'products.in_stock': 'স্টকে আছে',
  'products.out_of_stock': 'স্টকে নেই',
  'products.no_products': 'কোন পণ্য পাওয়া যায়নি',
  
  'storefront.title': 'আমার স্টোর',
  'storefront.share': 'স্টোর শেয়ার করুন',
  'storefront.add_to_cart': 'কার্টে যোগ করুন',
  'storefront.checkout': 'চেকআউট',
  'storefront.cart': 'কার্ট',
  
  'support.title': 'সাপোর্ট',
  'support.chat': 'লাইভ চ্যাট',
  'support.faq': 'সচরাচর জিজ্ঞাসা',
  'support.contact': 'যোগাযোগ করুন',
  'support.send': 'পাঠান',
  
  'landing.hero_title': 'আপনার ড্রপশিপিং ব্যবসা শুরু করুন',
  'landing.hero_subtitle': 'আধুনিক ড্রপশিপিং প্ল্যাটফর্ম। আপনার ড্রপশিপারদের ক্ষমতায়ন করুন। একসাথে বৃদ্ধি পান।',
  'landing.get_started': 'বিনামূল্যে শুরু করুন',
  'landing.track_order': 'অর্ডার ট্র্যাক করুন',
  'landing.sign_in': 'সাইন ইন করুন',
  
  'error.generic': 'কিছু ভুল হয়েছে',
  'error.network': 'নেটওয়ার্ক ত্রুটি। আবার চেষ্টা করুন।',
  'error.try_again': 'আবার চেষ্টা করুন',
};

// Marathi translations
const mrTranslations: Record<string, string> = {
  'common.loading': 'लोड होत आहे...',
  'common.save': 'जतन करा',
  'common.cancel': 'रद्द करा',
  'common.delete': 'हटवा',
  'common.edit': 'संपादित करा',
  'common.submit': 'सबमिट करा',
  'common.confirm': 'पुष्टी करा',
  'common.back': 'मागे',
  'common.next': 'पुढे',
  'common.search': 'शोधा',
  'common.filter': 'फिल्टर',
  'common.refresh': 'रीफ्रेश',
  'common.close': 'बंद करा',
  'common.view': 'पहा',
  'common.yes': 'होय',
  'common.no': 'नाही',
  'common.status': 'स्थिती',
  'common.date': 'तारीख',
  'common.amount': 'रक्कम',
  'common.total': 'एकूण',
  'common.success': 'यशस्वी',
  'common.error': 'त्रुटी',
  'common.pending': 'प्रलंबित',
  'common.approved': 'मंजूर',
  'common.completed': 'पूर्ण',
  'common.copied': 'कॉपी झाले!',
  
  'nav.dashboard': 'डॅशबोर्ड',
  'nav.profile': 'प्रोफाइल',
  'nav.storefront': 'माझे दुकान',
  'nav.products': 'उत्पादने ब्राउझ करा',
  'nav.orders': 'ऑर्डर',
  'nav.payments': 'पेमेंट',
  'nav.workspace': 'कार्यक्षेत्र',
  'nav.support': 'सहाय्य',
  'nav.help': 'मदत आणि FAQ',
  'nav.logout': 'लॉग आउट',
  'nav.settings': 'सेटिंग्ज',
  'nav.home': 'मुख्यपृष्ठ',
  'nav.chat': 'चॅट',
  'nav.notifications': 'सूचना',
  
  'profile.title': 'माझे प्रोफाइल',
  'profile.description': 'तुमची प्रोफाइल माहिती, सुरक्षा सेटिंग्ज आणि क्रियाकलाप पहा.',
  'profile.appearance': 'दिसावट',
  'profile.language': 'भाषा',
  'profile.security': 'सुरक्षा',
  'profile.change_password': 'पासवर्ड बदला',
  
  'auth.login': 'लॉग इन',
  'auth.signup': 'साइन अप',
  'auth.password': 'पासवर्ड',
  'auth.forgot_password': 'पासवर्ड विसरलात?',
  'auth.welcome_back': 'पुन्हा स्वागत आहे',
  'auth.create_account': 'खाते तयार करा',
  
  'dashboard.welcome': 'पुन्हा स्वागत आहे',
  'dashboard.total_orders': 'एकूण ऑर्डर',
  'dashboard.wallet_balance': 'वॉलेट शिल्लक',
  'dashboard.total_earnings': 'एकूण कमाई',
  'dashboard.recent_orders': 'अलीकडील ऑर्डर',
  'dashboard.view_all': 'सर्व पहा',
  'dashboard.revenue': 'महसूल',
  'dashboard.profit': 'नफा',
  
  'orders.title': 'ऑर्डर',
  'orders.new_order': 'नवीन ऑर्डर',
  'orders.order_number': 'ऑर्डर क्रमांक',
  'orders.customer': 'ग्राहक',
  'orders.product': 'उत्पादन',
  'orders.quantity': 'प्रमाण',
  'orders.price': 'किंमत',
  'orders.pending': 'प्रलंबित',
  'orders.completed': 'पूर्ण',
  'orders.cancelled': 'रद्द',
  'orders.no_orders': 'कोणतेही ऑर्डर सापडले नाहीत',
  
  'payments.title': 'पेमेंट',
  'payments.request_payout': 'पेआउट विनंती',
  'payments.balance': 'शिल्लक',
  'payments.bank_transfer': 'बँक ट्रान्सफर',
  
  'products.title': 'उत्पादने',
  'products.add_to_store': 'दुकानात जोडा',
  'products.price': 'किंमत',
  'products.stock': 'स्टॉक',
  'products.in_stock': 'स्टॉकमध्ये',
  'products.out_of_stock': 'स्टॉक संपला',
  
  'storefront.title': 'माझे दुकान',
  'storefront.add_to_cart': 'कार्टमध्ये जोडा',
  'storefront.checkout': 'चेकआउट',
  
  'support.title': 'सहाय्य',
  'support.chat': 'लाइव्ह चॅट',
  'support.faq': 'वारंवार विचारले जाणारे प्रश्न',
  
  'landing.hero_title': 'तुमचा ड्रॉपशिपिंग व्यवसाय सुरू करा',
  'landing.get_started': 'मोफत सुरू करा',
  'landing.sign_in': 'साइन इन करा',
  
  'error.generic': 'काहीतरी चूक झाली',
  'error.try_again': 'पुन्हा प्रयत्न करा',
};

// Tamil translations
const taTranslations: Record<string, string> = {
  'common.loading': 'ஏற்றுகிறது...',
  'common.save': 'சேமி',
  'common.cancel': 'ரத்துசெய்',
  'common.delete': 'நீக்கு',
  'common.edit': 'திருத்து',
  'common.submit': 'சமர்ப்பி',
  'common.confirm': 'உறுதிசெய்',
  'common.back': 'பின்',
  'common.next': 'அடுத்து',
  'common.search': 'தேடு',
  'common.filter': 'வடிகட்டி',
  'common.refresh': 'புதுப்பி',
  'common.close': 'மூடு',
  'common.view': 'காண்',
  'common.download': 'பதிவிறக்கு',
  'common.upload': 'பதிவேற்று',
  'common.yes': 'ஆம்',
  'common.no': 'இல்லை',
  'common.status': 'நிலை',
  'common.date': 'தேதி',
  'common.amount': 'தொகை',
  'common.total': 'மொத்தம்',
  'common.details': 'விவரங்கள்',
  'common.success': 'வெற்றி',
  'common.error': 'பிழை',
  'common.warning': 'எச்சரிக்கை',
  'common.all': 'அனைத்தும்',
  'common.pending': 'நிலுவையில்',
  'common.approved': 'அங்கீகரிக்கப்பட்டது',
  'common.completed': 'முடிந்தது',
  'common.copied': 'நகலெடுக்கப்பட்டது!',
  
  'nav.dashboard': 'டாஷ்போர்ட்',
  'nav.profile': 'சுயவிவரம்',
  'nav.storefront': 'என் கடை',
  'nav.products': 'பொருட்கள்',
  'nav.orders': 'ஆர்டர்கள்',
  'nav.payments': 'கொடுப்பனவுகள்',
  'nav.workspace': 'பணியிடம்',
  'nav.support': 'ஆதரவு',
  'nav.help': 'உதவி',
  'nav.logout': 'வெளியேறு',
  'nav.settings': 'அமைப்புகள்',
  'nav.home': 'முகப்பு',
  'nav.chat': 'அரட்டை',
  'nav.notifications': 'அறிவிப்புகள்',
  
  'profile.title': 'என் சுயவிவரம்',
  'profile.description': 'உங்கள் சுயவிவர தகவல், பாதுகாப்பு அமைப்புகள் மற்றும் செயல்பாட்டைக் காணலாம்.',
  'profile.appearance': 'தோற்றம்',
  'profile.language': 'மொழி',
  'profile.security': 'பாதுகாப்பு',
  'profile.change_password': 'கடவுச்சொல்லை மாற்று',
  
  'auth.login': 'உள்நுழை',
  'auth.signup': 'பதிவுசெய்',
  'auth.password': 'கடவுச்சொல்',
  'auth.forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
  'auth.welcome_back': 'மீண்டும் வரவேற்கிறோம்',
  'auth.sign_in_desc': 'உங்கள் டாஷ்போர்டை அணுக உள்நுழையவும்',
  'auth.create_account': 'கணக்கை உருவாக்கு',
  
  'dashboard.welcome': 'மீண்டும் வரவேற்கிறோம்',
  'dashboard.total_orders': 'மொத்த ஆர்டர்கள்',
  'dashboard.pending_orders': 'நிலுவை ஆர்டர்கள்',
  'dashboard.wallet_balance': 'வாலட் இருப்பு',
  'dashboard.total_earnings': 'மொத்த வருமானம்',
  'dashboard.recent_orders': 'சமீபத்திய ஆர்டர்கள்',
  'dashboard.view_all': 'அனைத்தையும் காண்',
  'dashboard.revenue': 'வருவாய்',
  'dashboard.profit': 'லாபம்',
  'dashboard.commission': 'கமிஷன்',
  
  'orders.title': 'ஆர்டர்கள்',
  'orders.new_order': 'புதிய ஆர்டர்',
  'orders.order_number': 'ஆர்டர் எண்',
  'orders.customer': 'வாடிக்கையாளர்',
  'orders.product': 'பொருள்',
  'orders.quantity': 'அளவு',
  'orders.price': 'விலை',
  'orders.total': 'மொத்தம்',
  'orders.pending': 'நிலுவையில்',
  'orders.completed': 'முடிந்தது',
  'orders.cancelled': 'ரத்துசெய்யப்பட்டது',
  'orders.no_orders': 'ஆர்டர்கள் இல்லை',
  'orders.place_order': 'ஆர்டர் செய்',
  
  'payments.title': 'கொடுப்பனவுகள்',
  'payments.request_payout': 'கொடுப்பனவு கோரிக்கை',
  'payments.balance': 'இருப்பு',
  'payments.bank_transfer': 'வங்கி பரிமாற்றம்',
  'payments.upi': 'யுபிஐ',
  'payments.no_transactions': 'பரிவர்த்தனைகள் இல்லை',
  
  'products.title': 'பொருட்கள்',
  'products.add_to_store': 'கடையில் சேர்',
  'products.price': 'விலை',
  'products.stock': 'இருப்பு',
  'products.in_stock': 'இருப்பில் உள்ளது',
  'products.out_of_stock': 'இருப்பில் இல்லை',
  'products.no_products': 'பொருட்கள் இல்லை',
  
  'storefront.title': 'என் கடை',
  'storefront.add_to_cart': 'கார்ட்டில் சேர்',
  'storefront.checkout': 'செக்அவுட்',
  
  'support.title': 'ஆதரவு',
  'support.chat': 'நேரடி அரட்டை',
  'support.faq': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
  
  'landing.hero_title': 'உங்கள் டிராப்ஷிப்பிங் வணிகத்தைத் தொடங்குங்கள்',
  'landing.hero_subtitle': 'நவீன டிராப்ஷிப்பிங் தளம். உங்கள் டிராப்ஷிப்பர்களுக்கு அதிகாரம் அளியுங்கள். ஒன்றாக வளருங்கள்.',
  'landing.get_started': 'இலவசமாகத் தொடங்குங்கள்',
  'landing.sign_in': 'உள்நுழைக',
  
  'error.generic': 'ஏதோ தவறு நடந்தது',
  'error.try_again': 'மீண்டும் முயற்சி',
};

// Telugu translations
const teTranslations: Record<string, string> = {
  'common.loading': 'లోడ్ అవుతోంది...',
  'common.save': 'సేవ్ చేయి',
  'common.cancel': 'రద్దు చేయి',
  'common.delete': 'తొలగించు',
  'common.edit': 'సవరించు',
  'common.submit': 'సమర్పించు',
  'common.confirm': 'నిర్ధారించు',
  'common.back': 'వెనుకకు',
  'common.next': 'తదుపరి',
  'common.search': 'వెతుకు',
  'common.filter': 'ఫిల్టర్',
  'common.refresh': 'రిఫ్రెష్',
  'common.close': 'మూసివేయు',
  'common.view': 'చూడండి',
  'common.yes': 'అవును',
  'common.no': 'కాదు',
  'common.status': 'స్థితి',
  'common.date': 'తేదీ',
  'common.amount': 'మొత్తం',
  'common.total': 'మొత్తం',
  'common.success': 'విజయం',
  'common.error': 'లోపం',
  'common.pending': 'పెండింగ్',
  'common.approved': 'ఆమోదించబడింది',
  'common.completed': 'పూర్తయింది',
  'common.copied': 'కాపీ చేయబడింది!',
  
  'nav.dashboard': 'డాష్‌బోర్డ్',
  'nav.profile': 'ప్రొఫైల్',
  'nav.storefront': 'నా స్టోర్',
  'nav.products': 'ఉత్పత్తులు',
  'nav.orders': 'ఆర్డర్లు',
  'nav.payments': 'చెల్లింపులు',
  'nav.workspace': 'వర్క్‌స్పేస్',
  'nav.support': 'మద్దతు',
  'nav.help': 'సహాయం',
  'nav.logout': 'లాగ్ అవుట్',
  'nav.settings': 'సెట్టింగ్‌లు',
  'nav.home': 'హోమ్',
  'nav.chat': 'చాట్',
  'nav.notifications': 'నోటిఫికేషన్లు',
  
  'profile.title': 'నా ప్రొఫైల్',
  'profile.description': 'మీ ప్రొఫైల్ సమాచారం, భద్రతా సెట్టింగ్‌లు మరియు కార్యకలాపాలను చూడండి.',
  'profile.appearance': 'రూపం',
  'profile.language': 'భాష',
  'profile.security': 'భద్రత',
  'profile.change_password': 'పాస్‌వర్డ్ మార్చు',
  
  'auth.login': 'లాగిన్',
  'auth.signup': 'సైన్ అప్',
  'auth.password': 'పాస్‌వర్డ్',
  'auth.forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
  'auth.welcome_back': 'తిరిగి స్వాగతం',
  'auth.sign_in_desc': 'మీ డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి',
  'auth.create_account': 'ఖాతాను సృష్టించు',
  
  'dashboard.welcome': 'తిరిగి స్వాగతం',
  'dashboard.total_orders': 'మొత్తం ఆర్డర్లు',
  'dashboard.pending_orders': 'పెండింగ్ ఆర్డర్లు',
  'dashboard.wallet_balance': 'వాలెట్ బ్యాలెన్స్',
  'dashboard.total_earnings': 'మొత్తం ఆదాయం',
  'dashboard.recent_orders': 'ఇటీవలి ఆర్డర్లు',
  'dashboard.view_all': 'అన్నీ చూడండి',
  'dashboard.revenue': 'ఆదాయం',
  'dashboard.profit': 'లాభం',
  'dashboard.commission': 'కమీషన్',
  
  'orders.title': 'ఆర్డర్లు',
  'orders.new_order': 'కొత్త ఆర్డర్',
  'orders.order_number': 'ఆర్డర్ నంబర్',
  'orders.customer': 'కస్టమర్',
  'orders.product': 'ఉత్పత్తి',
  'orders.quantity': 'పరిమాణం',
  'orders.price': 'ధర',
  'orders.pending': 'పెండింగ్',
  'orders.completed': 'పూర్తయింది',
  'orders.cancelled': 'రద్దు చేయబడింది',
  'orders.no_orders': 'ఆర్డర్లు కనుగొనబడలేదు',
  'orders.place_order': 'ఆర్డర్ చేయండి',
  
  'payments.title': 'చెల్లింపులు',
  'payments.request_payout': 'పేఅవుట్ అభ్యర్థన',
  'payments.balance': 'బ్యాలెన్స్',
  'payments.bank_transfer': 'బ్యాంక్ బదిలీ',
  'payments.upi': 'యుపిఐ',
  'payments.no_transactions': 'లావాదేవీలు కనుగొనబడలేదు',
  
  'products.title': 'ఉత్పత్తులు',
  'products.add_to_store': 'స్టోర్‌కు జోడించండి',
  'products.price': 'ధర',
  'products.stock': 'స్టాక్',
  'products.in_stock': 'స్టాక్‌లో ఉంది',
  'products.out_of_stock': 'స్టాక్‌లో లేదు',
  'products.no_products': 'ఉత్పత్తులు కనుగొనబడలేదు',
  
  'storefront.title': 'నా స్టోర్',
  'storefront.add_to_cart': 'కార్ట్‌కు జోడించండి',
  'storefront.checkout': 'చెక్అవుట్',
  
  'support.title': 'మద్దతు',
  'support.chat': 'లైవ్ చాట్',
  'support.faq': 'తరచుగా అడిగే ప్రశ్నలు',
  
  'landing.hero_title': 'మీ డ్రాప్‌షిప్పింగ్ వ్యాపారాన్ని ప్రారంభించండి',
  'landing.hero_subtitle': 'ఆధునిక డ్రాప్‌షిప్పింగ్ ప్లాట్‌ఫామ్. మీ డ్రాప్‌షిప్పర్లకు సాధికారత ఇవ్వండి. కలిసి అభివృద్ధి చెందండి.',
  'landing.get_started': 'ఉచితంగా ప్రారంభించండి',
  'landing.sign_in': 'సైన్ ఇన్',
  
  'error.generic': 'ఏదో తప్పు జరిగింది',
  'error.try_again': 'మళ్ళీ ప్రయత్నించండి',
};

// Gujarati translations
const guTranslations: Record<string, string> = {
  'common.loading': 'લોડ થઈ રહ્યું છે...',
  'common.save': 'સાચવો',
  'common.cancel': 'રદ કરો',
  'common.delete': 'કાઢી નાખો',
  'common.edit': 'સંપાદિત કરો',
  'common.submit': 'સબમિટ કરો',
  'common.confirm': 'પુષ્ટિ કરો',
  'common.back': 'પાછળ',
  'common.next': 'આગળ',
  'common.search': 'શોધો',
  'common.yes': 'હા',
  'common.no': 'ના',
  'common.status': 'સ્થિતિ',
  'common.amount': 'રકમ',
  'common.total': 'કુલ',
  'common.success': 'સફળ',
  'common.error': 'ભૂલ',
  'common.pending': 'બાકી',
  'common.completed': 'પૂર્ણ',
  'common.copied': 'કોપી થયું!',
  
  'nav.dashboard': 'ડેશબોર્ડ',
  'nav.profile': 'પ્રોફાઇલ',
  'nav.storefront': 'મારી દુકાન',
  'nav.products': 'ઉત્પાદનો',
  'nav.orders': 'ઓર્ડર',
  'nav.payments': 'ચૂકવણી',
  'nav.support': 'સહાય',
  'nav.help': 'મદદ',
  'nav.logout': 'લોગ આઉટ',
  'nav.settings': 'સેટિંગ્સ',
  'nav.home': 'હોમ',
  
  'profile.title': 'મારી પ્રોફાઇલ',
  'profile.appearance': 'દેખાવ',
  'profile.language': 'ભાષા',
  'profile.security': 'સુરક્ષા',
  
  'auth.login': 'લોગ ઇન',
  'auth.signup': 'સાઇન અપ',
  'auth.password': 'પાસવર્ડ',
  'auth.welcome_back': 'ફરી સ્વાગત છે',
  'auth.create_account': 'એકાઉન્ટ બનાવો',
  
  'dashboard.welcome': 'ફરી સ્વાગત છે',
  'dashboard.total_orders': 'કુલ ઓર્ડર',
  'dashboard.wallet_balance': 'વોલેટ બેલેન્સ',
  'dashboard.total_earnings': 'કુલ કમાણી',
  'dashboard.view_all': 'બધું જુઓ',
  
  'orders.title': 'ઓર્ડર',
  'orders.customer': 'ગ્રાહક',
  'orders.product': 'ઉત્પાદન',
  'orders.price': 'કિંમત',
  'orders.pending': 'બાકી',
  'orders.completed': 'પૂર્ણ',
  'orders.no_orders': 'કોઈ ઓર્ડર મળ્યા નથી',
  
  'payments.title': 'ચૂકવણી',
  'payments.balance': 'બેલેન્સ',
  'payments.bank_transfer': 'બેંક ટ્રાન્સફર',
  
  'products.title': 'ઉત્પાદનો',
  'products.price': 'કિંમત',
  'products.stock': 'સ્ટોક',
  'products.in_stock': 'સ્ટોકમાં છે',
  'products.out_of_stock': 'સ્ટોક નથી',
  
  'storefront.title': 'મારી દુકાન',
  'storefront.add_to_cart': 'કાર્ટમાં ઉમેરો',
  
  'support.title': 'સહાય',
  'support.chat': 'લાઇવ ચેટ',
  
  'landing.hero_title': 'તમારો ડ્રોપશિપિંગ વ્યવસાય શરૂ કરો',
  'landing.get_started': 'મફતમાં શરૂ કરો',
  'landing.sign_in': 'સાઇન ઇન',
  
  'error.generic': 'કંઈક ખોટું થયું',
  'error.try_again': 'ફરી પ્રયત્ન કરો',
};

// Kannada translations
const knTranslations: Record<string, string> = {
  'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
  'common.save': 'ಉಳಿಸಿ',
  'common.cancel': 'ರದ್ದುಮಾಡಿ',
  'common.delete': 'ಅಳಿಸಿ',
  'common.edit': 'ಸಂಪಾದಿಸಿ',
  'common.submit': 'ಸಲ್ಲಿಸಿ',
  'common.confirm': 'ದೃಢೀಕರಿಸಿ',
  'common.back': 'ಹಿಂದೆ',
  'common.next': 'ಮುಂದೆ',
  'common.search': 'ಹುಡುಕಿ',
  'common.yes': 'ಹೌದು',
  'common.no': 'ಇಲ್ಲ',
  'common.status': 'ಸ್ಥಿತಿ',
  'common.amount': 'ಮೊತ್ತ',
  'common.total': 'ಒಟ್ಟು',
  'common.success': 'ಯಶಸ್ಸು',
  'common.error': 'ದೋಷ',
  'common.pending': 'ಬಾಕಿ',
  'common.completed': 'ಪೂರ್ಣ',
  'common.copied': 'ನಕಲು ಮಾಡಲಾಗಿದೆ!',
  
  'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  'nav.profile': 'ಪ್ರೊಫೈಲ್',
  'nav.storefront': 'ನನ್ನ ಅಂಗಡಿ',
  'nav.products': 'ಉತ್ಪನ್ನಗಳು',
  'nav.orders': 'ಆದೇಶಗಳು',
  'nav.payments': 'ಪಾವತಿಗಳು',
  'nav.support': 'ಬೆಂಬಲ',
  'nav.help': 'ಸಹಾಯ',
  'nav.logout': 'ಲಾಗ್ ಔಟ್',
  'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
  'nav.home': 'ಮುಖಪುಟ',
  
  'profile.title': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
  'profile.appearance': 'ನೋಟ',
  'profile.language': 'ಭಾಷೆ',
  'profile.security': 'ಭದ್ರತೆ',
  
  'auth.login': 'ಲಾಗಿನ್',
  'auth.signup': 'ಸೈನ್ ಅಪ್',
  'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
  'auth.welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ',
  'auth.create_account': 'ಖಾತೆ ರಚಿಸಿ',
  
  'dashboard.welcome': 'ಮರಳಿ ಸ್ವಾಗತ',
  'dashboard.total_orders': 'ಒಟ್ಟು ಆದೇಶಗಳು',
  'dashboard.wallet_balance': 'ವ್ಯಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್',
  'dashboard.total_earnings': 'ಒಟ್ಟು ಗಳಿಕೆ',
  'dashboard.view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
  
  'orders.title': 'ಆದೇಶಗಳು',
  'orders.customer': 'ಗ್ರಾಹಕ',
  'orders.product': 'ಉತ್ಪನ್ನ',
  'orders.price': 'ಬೆಲೆ',
  'orders.pending': 'ಬಾಕಿ',
  'orders.completed': 'ಪೂರ್ಣ',
  'orders.no_orders': 'ಯಾವುದೇ ಆದೇಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
  
  'payments.title': 'ಪಾವತಿಗಳು',
  'payments.balance': 'ಬ್ಯಾಲೆನ್ಸ್',
  'payments.bank_transfer': 'ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ',
  
  'products.title': 'ಉತ್ಪನ್ನಗಳು',
  'products.price': 'ಬೆಲೆ',
  'products.stock': 'ಸ್ಟಾಕ್',
  'products.in_stock': 'ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ',
  'products.out_of_stock': 'ಸ್ಟಾಕ್‌ನಲ್ಲಿಲ್ಲ',
  
  'storefront.title': 'ನನ್ನ ಅಂಗಡಿ',
  'storefront.add_to_cart': 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
  
  'support.title': 'ಬೆಂಬಲ',
  'support.chat': 'ಲೈವ್ ಚಾಟ್',
  
  'landing.hero_title': 'ನಿಮ್ಮ ಡ್ರಾಪ್‌ಶಿಪ್ಪಿಂಗ್ ವ್ಯಾಪಾರವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
  'landing.get_started': 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
  'landing.sign_in': 'ಸೈನ್ ಇನ್',
  
  'error.generic': 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
  'error.try_again': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
};

// Malayalam translations
const mlTranslations: Record<string, string> = {
  'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
  'common.save': 'സേവ് ചെയ്യുക',
  'common.cancel': 'റദ്ദാക്കുക',
  'common.delete': 'ഇല്ലാതാക്കുക',
  'common.edit': 'എഡിറ്റ് ചെയ്യുക',
  'common.submit': 'സമർപ്പിക്കുക',
  'common.confirm': 'സ്ഥിരീകരിക്കുക',
  'common.back': 'പിന്നിലേക്ക്',
  'common.next': 'അടുത്തത്',
  'common.search': 'തിരയുക',
  'common.yes': 'അതെ',
  'common.no': 'ഇല്ല',
  'common.status': 'സ്ഥിതി',
  'common.amount': 'തുക',
  'common.total': 'ആകെ',
  'common.success': 'വിജയം',
  'common.error': 'പിശക്',
  'common.pending': 'തീർപ്പാക്കാത്ത',
  'common.completed': 'പൂർത്തിയായി',
  'common.copied': 'കോപ്പി ചെയ്തു!',
  
  'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
  'nav.profile': 'പ്രൊഫൈൽ',
  'nav.storefront': 'എന്റെ കട',
  'nav.products': 'ഉൽപ്പന്നങ്ങൾ',
  'nav.orders': 'ഓർഡറുകൾ',
  'nav.payments': 'പേയ്‌മെന്റുകൾ',
  'nav.support': 'പിന്തുണ',
  'nav.help': 'സഹായം',
  'nav.logout': 'ലോഗ് ഔട്ട്',
  'nav.settings': 'ക്രമീകരണങ്ങൾ',
  'nav.home': 'ഹോം',
  
  'profile.title': 'എന്റെ പ്രൊഫൈൽ',
  'profile.appearance': 'രൂപം',
  'profile.language': 'ഭാഷ',
  'profile.security': 'സുരക്ഷ',
  
  'auth.login': 'ലോഗിൻ',
  'auth.signup': 'സൈൻ അപ്പ്',
  'auth.password': 'പാസ്‌വേഡ്',
  'auth.welcome_back': 'തിരികെ സ്വാഗതം',
  'auth.create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
  
  'dashboard.welcome': 'തിരികെ സ്വാഗതം',
  'dashboard.total_orders': 'ആകെ ഓർഡറുകൾ',
  'dashboard.wallet_balance': 'വാലറ്റ് ബാലൻസ്',
  'dashboard.total_earnings': 'ആകെ വരുമാനം',
  'dashboard.view_all': 'എല്ലാം കാണുക',
  
  'orders.title': 'ഓർഡറുകൾ',
  'orders.customer': 'ഉപഭോക്താവ്',
  'orders.product': 'ഉൽപ്പന്നം',
  'orders.price': 'വില',
  'orders.pending': 'തീർപ്പാക്കാത്ത',
  'orders.completed': 'പൂർത്തിയായി',
  'orders.no_orders': 'ഓർഡറുകളൊന്നും കണ്ടെത്തിയില്ല',
  
  'payments.title': 'പേയ്‌മെന്റുകൾ',
  'payments.balance': 'ബാലൻസ്',
  'payments.bank_transfer': 'ബാങ്ക് ട്രാൻസ്ഫർ',
  
  'products.title': 'ഉൽപ്പന്നങ്ങൾ',
  'products.price': 'വില',
  'products.stock': 'സ്റ്റോക്ക്',
  'products.in_stock': 'സ്റ്റോക്കിലുണ്ട്',
  'products.out_of_stock': 'സ്റ്റോക്കില്ല',
  
  'storefront.title': 'എന്റെ കട',
  'storefront.add_to_cart': 'കാർട്ടിലേക്ക് ചേർക്കുക',
  
  'support.title': 'പിന്തുണ',
  'support.chat': 'ലൈവ് ചാറ്റ്',
  
  'landing.hero_title': 'നിങ്ങളുടെ ഡ്രോപ്‌ഷിപ്പിംഗ് ബിസിനസ്സ് ആരംഭിക്കുക',
  'landing.get_started': 'സൗജന്യമായി ആരംഭിക്കുക',
  'landing.sign_in': 'സൈൻ ഇൻ',
  
  'error.generic': 'എന്തോ കുഴപ്പം സംഭവിച്ചു',
  'error.try_again': 'വീണ്ടും ശ്രമിക്കുക',
};

// Punjabi translations
const paTranslations: Record<string, string> = {
  'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
  'common.save': 'ਸੇਵ ਕਰੋ',
  'common.cancel': 'ਰੱਦ ਕਰੋ',
  'common.delete': 'ਮਿਟਾਓ',
  'common.edit': 'ਸੋਧੋ',
  'common.submit': 'ਜਮ੍ਹਾਂ ਕਰੋ',
  'common.confirm': 'ਪੁਸ਼ਟੀ ਕਰੋ',
  'common.back': 'ਪਿੱਛੇ',
  'common.next': 'ਅੱਗੇ',
  'common.search': 'ਖੋਜੋ',
  'common.yes': 'ਹਾਂ',
  'common.no': 'ਨਹੀਂ',
  'common.status': 'ਸਥਿਤੀ',
  'common.amount': 'ਰਕਮ',
  'common.total': 'ਕੁੱਲ',
  'common.success': 'ਸਫਲ',
  'common.error': 'ਗਲਤੀ',
  'common.pending': 'ਬਕਾਇਆ',
  'common.completed': 'ਪੂਰਾ',
  'common.copied': 'ਕਾਪੀ ਹੋ ਗਿਆ!',
  
  'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
  'nav.profile': 'ਪ੍ਰੋਫਾਈਲ',
  'nav.storefront': 'ਮੇਰੀ ਦੁਕਾਨ',
  'nav.products': 'ਉਤਪਾਦ',
  'nav.orders': 'ਆਰਡਰ',
  'nav.payments': 'ਭੁਗਤਾਨ',
  'nav.support': 'ਸਹਾਇਤਾ',
  'nav.help': 'ਮਦਦ',
  'nav.logout': 'ਲੌਗ ਆਊਟ',
  'nav.settings': 'ਸੈਟਿੰਗਾਂ',
  'nav.home': 'ਘਰ',
  
  'profile.title': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
  'profile.appearance': 'ਦਿੱਖ',
  'profile.language': 'ਭਾਸ਼ਾ',
  'profile.security': 'ਸੁਰੱਖਿਆ',
  
  'auth.login': 'ਲੌਗ ਇਨ',
  'auth.signup': 'ਸਾਈਨ ਅੱਪ',
  'auth.password': 'ਪਾਸਵਰਡ',
  'auth.welcome_back': 'ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ ਹੈ',
  'auth.create_account': 'ਖਾਤਾ ਬਣਾਓ',
  
  'dashboard.welcome': 'ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ ਹੈ',
  'dashboard.total_orders': 'ਕੁੱਲ ਆਰਡਰ',
  'dashboard.wallet_balance': 'ਵਾਲਿਟ ਬੈਲੇਂਸ',
  'dashboard.total_earnings': 'ਕੁੱਲ ਕਮਾਈ',
  'dashboard.view_all': 'ਸਭ ਦੇਖੋ',
  
  'orders.title': 'ਆਰਡਰ',
  'orders.customer': 'ਗਾਹਕ',
  'orders.product': 'ਉਤਪਾਦ',
  'orders.price': 'ਕੀਮਤ',
  'orders.pending': 'ਬਕਾਇਆ',
  'orders.completed': 'ਪੂਰਾ',
  'orders.no_orders': 'ਕੋਈ ਆਰਡਰ ਨਹੀਂ ਮਿਲੇ',
  
  'payments.title': 'ਭੁਗਤਾਨ',
  'payments.balance': 'ਬੈਲੇਂਸ',
  'payments.bank_transfer': 'ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ',
  
  'products.title': 'ਉਤਪਾਦ',
  'products.price': 'ਕੀਮਤ',
  'products.stock': 'ਸਟਾਕ',
  'products.in_stock': 'ਸਟਾਕ ਵਿੱਚ ਹੈ',
  'products.out_of_stock': 'ਸਟਾਕ ਖਤਮ',
  
  'storefront.title': 'ਮੇਰੀ ਦੁਕਾਨ',
  'storefront.add_to_cart': 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
  
  'support.title': 'ਸਹਾਇਤਾ',
  'support.chat': 'ਲਾਈਵ ਚੈਟ',
  
  'landing.hero_title': 'ਆਪਣਾ ਡ੍ਰੌਪਸ਼ਿਪਿੰਗ ਕਾਰੋਬਾਰ ਸ਼ੁਰੂ ਕਰੋ',
  'landing.get_started': 'ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ',
  'landing.sign_in': 'ਸਾਈਨ ਇਨ',
  
  'error.generic': 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
  'error.try_again': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
};

// Odia translations
const orTranslations: Record<string, string> = {
  'common.loading': 'ଲୋଡ଼ ହେଉଛି...',
  'common.save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
  'common.cancel': 'ବାତିଲ କରନ୍ତୁ',
  'common.delete': 'ବିଲୋପ କରନ୍ତୁ',
  'common.edit': 'ସମ୍ପାଦନା କରନ୍ତୁ',
  'common.submit': 'ଦାଖଲ କରନ୍ତୁ',
  'common.confirm': 'ନିଶ୍ଚିତ କରନ୍ତୁ',
  'common.back': 'ପଛକୁ',
  'common.next': 'ପରବର୍ତ୍ତୀ',
  'common.search': 'ଖୋଜନ୍ତୁ',
  'common.yes': 'ହଁ',
  'common.no': 'ନା',
  'common.status': 'ସ୍ଥିତି',
  'common.amount': 'ପରିମାଣ',
  'common.total': 'ମୋଟ',
  'common.success': 'ସଫଳ',
  'common.error': 'ତ୍ରୁଟି',
  'common.pending': 'ବାକି',
  'common.completed': 'ସମ୍ପୂର୍ଣ୍ଣ',
  'common.copied': 'କପି ହୋଇଛି!',
  
  'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ଼',
  'nav.profile': 'ପ୍ରୋଫାଇଲ',
  'nav.storefront': 'ମୋର ଦୋକାନ',
  'nav.products': 'ଉତ୍ପାଦ',
  'nav.orders': 'ଅର୍ଡର',
  'nav.payments': 'ଦେୟ',
  'nav.support': 'ସହାୟତା',
  'nav.help': 'ସାହାଯ୍ୟ',
  'nav.logout': 'ଲଗଆଉଟ',
  'nav.settings': 'ସେଟିଂ',
  'nav.home': 'ଘର',
  
  'profile.title': 'ମୋର ପ୍ରୋଫାଇଲ',
  'profile.appearance': 'ଦୃଶ୍ୟ',
  'profile.language': 'ଭାଷା',
  'profile.security': 'ସୁରକ୍ଷା',
  
  'auth.login': 'ଲଗଇନ',
  'auth.signup': 'ସାଇନ ଅପ',
  'auth.password': 'ପାସୱାର୍ଡ',
  'auth.welcome_back': 'ପୁଣି ସ୍ୱାଗତ',
  'auth.create_account': 'ଆକାଉଣ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ',
  
  'dashboard.welcome': 'ପୁଣି ସ୍ୱାଗତ',
  'dashboard.total_orders': 'ମୋଟ ଅର୍ଡର',
  'dashboard.wallet_balance': 'ୱାଲେଟ ବାଲାନ୍ସ',
  'dashboard.total_earnings': 'ମୋଟ ଆୟ',
  'dashboard.view_all': 'ସବୁ ଦେଖନ୍ତୁ',
  
  'orders.title': 'ଅର୍ଡର',
  'orders.customer': 'ଗ୍ରାହକ',
  'orders.product': 'ଉତ୍ପାଦ',
  'orders.price': 'ମୂଲ୍ୟ',
  'orders.pending': 'ବାକି',
  'orders.completed': 'ସମ୍ପୂର୍ଣ୍ଣ',
  'orders.no_orders': 'କୌଣସି ଅର୍ଡର ମିଳିଲା ନାହିଁ',
  
  'payments.title': 'ଦେୟ',
  'payments.balance': 'ବାଲାନ୍ସ',
  'payments.bank_transfer': 'ବ୍ୟାଙ୍କ ଟ୍ରାନ୍ସଫର',
  
  'products.title': 'ଉତ୍ପାଦ',
  'products.price': 'ମୂଲ୍ୟ',
  'products.stock': 'ଷ୍ଟକ',
  'products.in_stock': 'ଷ୍ଟକରେ ଅଛି',
  'products.out_of_stock': 'ଷ୍ଟକ ନାହିଁ',
  
  'storefront.title': 'ମୋର ଦୋକାନ',
  'storefront.add_to_cart': 'କାର୍ଟରେ ଯୋଡନ୍ତୁ',
  
  'support.title': 'ସହାୟତା',
  'support.chat': 'ଲାଇଭ ଚାଟ',
  
  'landing.hero_title': 'ଆପଣଙ୍କର ଡ୍ରପଶିପିଂ ବ୍ୟବସାୟ ଆରମ୍ଭ କରନ୍ତୁ',
  'landing.get_started': 'ମାଗଣାରେ ଆରମ୍ଭ କରନ୍ତୁ',
  'landing.sign_in': 'ସାଇନ ଇନ',
  
  'error.generic': 'କିଛି ଭୁଲ ହୋଇଗଲା',
  'error.try_again': 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
};

// Combine all translations
const translations: Record<Language, Record<string, string>> = {
  en: enTranslations,
  hi: hiTranslations,
  bn: bnTranslations,
  mr: mrTranslations,
  ta: taTranslations,
  te: teTranslations,
  gu: guTranslations,
  kn: knTranslations,
  ml: mlTranslations,
  pa: paTranslations,
  or: orTranslations,
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('preferred-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('preferred-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  }, [language]);

  const currentLanguage = languages.find(l => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
