import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te';

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguage: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.refresh': 'Refresh',
    'common.close': 'Close',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.total': 'Total',
    'common.details': 'Details',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.copy': 'Copy',
    'common.share': 'Share',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.storefront': 'My Storefront',
    'nav.products': 'Browse Products',
    'nav.orders': 'Orders',
    'nav.payments': 'Payments',
    'nav.workspace': 'Workspace',
    'nav.support': 'Support',
    'nav.help': 'Help',
    'nav.logout': 'Logout',
    'nav.settings': 'Settings',
    'nav.home': 'Home',
    'nav.chat': 'Chat',
    'nav.notifications': 'Notifications',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.description': 'View your profile information, security settings, and activity.',
    'profile.appearance': 'Appearance',
    'profile.appearance_desc': 'Choose your preferred theme for the dashboard',
    'profile.language': 'Language',
    'profile.language_desc': 'Select your preferred language',
    'profile.security': 'Security',
    'profile.change_password': 'Change Password',
    'profile.two_factor': 'Two-Factor Authentication',
    'profile.login_activity': 'Login Activity',
    'profile.account_info': 'Account Information',
    'profile.email': 'Email',
    'profile.name': 'Name',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgot_password': 'Forgot Password?',
    'auth.remember_me': 'Remember me',
    'auth.welcome_back': 'Welcome back',
    'auth.sign_in_desc': 'Sign in to access your dashboard',
    'auth.email_address': 'Email address',
    'auth.create_account': 'Create Account',
    'auth.already_have_account': 'Already have an account?',
    'auth.dont_have_account': "Don't have an account?",
    'auth.verify_email': 'Verify Email',
    'auth.resend_code': 'Resend Code',
    'auth.verification_code': 'Verification Code',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.total_orders': 'Total Orders',
    'dashboard.pending_orders': 'Pending Orders',
    'dashboard.wallet_balance': 'Wallet Balance',
    'dashboard.total_earnings': 'Total Earnings',
    'dashboard.recent_orders': 'Recent Orders',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.view_all': 'View All',
    'dashboard.todays_sales': "Today's Sales",
    'dashboard.this_week': 'This Week',
    'dashboard.this_month': 'This Month',
    'dashboard.growth': 'Growth',
    'dashboard.revenue': 'Revenue',
    'dashboard.profit': 'Profit',
    'dashboard.commission': 'Commission',
    
    // Orders
    'orders.title': 'Orders',
    'orders.new_order': 'New Order',
    'orders.order_number': 'Order Number',
    'orders.status': 'Status',
    'orders.customer': 'Customer',
    'orders.amount': 'Amount',
    'orders.date': 'Date',
    'orders.product': 'Product',
    'orders.quantity': 'Quantity',
    'orders.price': 'Price',
    'orders.total': 'Total',
    'orders.pending': 'Pending',
    'orders.processing': 'Processing',
    'orders.completed': 'Completed',
    'orders.cancelled': 'Cancelled',
    'orders.paid': 'Paid',
    'orders.unpaid': 'Unpaid',
    'orders.view_order': 'View Order',
    'orders.track_order': 'Track Order',
    'orders.order_details': 'Order Details',
    'orders.customer_info': 'Customer Information',
    'orders.shipping_address': 'Shipping Address',
    'orders.payment_status': 'Payment Status',
    'orders.order_history': 'Order History',
    'orders.no_orders': 'No orders found',
    'orders.place_order': 'Place Order',
    'orders.order_placed': 'Order Placed Successfully',
    'orders.pending_payment': 'Pending Payment',
    'orders.paid_by_user': 'Paid by User',
    'orders.postpaid_pending': 'Postpaid Pending',
    
    // Payments
    'payments.title': 'Payments',
    'payments.request_payout': 'Request Payout',
    'payments.add_funds': 'Add Funds',
    'payments.transaction_history': 'Transaction History',
    'payments.balance': 'Balance',
    'payments.available': 'Available',
    'payments.pending': 'Pending',
    'payments.payout_method': 'Payout Method',
    'payments.bank_transfer': 'Bank Transfer',
    'payments.upi': 'UPI',
    'payments.crypto': 'Cryptocurrency',
    'payments.amount': 'Amount',
    'payments.fee': 'Fee',
    'payments.net_amount': 'Net Amount',
    'payments.request_date': 'Request Date',
    'payments.processed_date': 'Processed Date',
    'payments.status': 'Status',
    'payments.approved': 'Approved',
    'payments.rejected': 'Rejected',
    'payments.processing': 'Processing',
    'payments.completed': 'Completed',
    'payments.no_transactions': 'No transactions found',
    'payments.minimum_payout': 'Minimum Payout',
    'payments.payment_details': 'Payment Details',
    'payments.bank_name': 'Bank Name',
    'payments.account_number': 'Account Number',
    'payments.ifsc_code': 'IFSC Code',
    'payments.account_holder': 'Account Holder Name',
    'payments.upi_id': 'UPI ID',
    'payments.wallet_address': 'Wallet Address',
    'payments.commission_earned': 'Commission Earned',
    'payments.payout_history': 'Payout History',
    
    // Products
    'products.title': 'Products',
    'products.browse': 'Browse Products',
    'products.add_to_store': 'Add to Store',
    'products.remove_from_store': 'Remove from Store',
    'products.price': 'Price',
    'products.base_price': 'Base Price',
    'products.selling_price': 'Selling Price',
    'products.profit_margin': 'Profit Margin',
    'products.stock': 'Stock',
    'products.in_stock': 'In Stock',
    'products.out_of_stock': 'Out of Stock',
    'products.category': 'Category',
    'products.description': 'Description',
    'products.sku': 'SKU',
    'products.no_products': 'No products found',
    'products.search_products': 'Search products...',
    'products.my_products': 'My Products',
    'products.all_products': 'All Products',
    
    // Storefront
    'storefront.title': 'My Storefront',
    'storefront.setup': 'Setup Storefront',
    'storefront.name': 'Store Name',
    'storefront.slug': 'Store URL',
    'storefront.banner': 'Store Banner',
    'storefront.products': 'Store Products',
    'storefront.share': 'Share Store',
    'storefront.copy_link': 'Copy Link',
    'storefront.preview': 'Preview Store',
    'storefront.settings': 'Store Settings',
    
    // Support
    'support.title': 'Support',
    'support.chat': 'Live Chat',
    'support.tickets': 'Support Tickets',
    'support.faq': 'FAQ',
    'support.contact': 'Contact Us',
    'support.new_ticket': 'New Ticket',
    'support.ticket_status': 'Ticket Status',
    'support.open': 'Open',
    'support.closed': 'Closed',
    'support.in_progress': 'In Progress',
    
    // Settings
    'settings.title': 'Settings',
    'settings.general': 'General',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.payment': 'Payment Settings',
    'settings.save_changes': 'Save Changes',
    
    // Landing Page
    'landing.hero_title': 'Start Your Dropshipping Business',
    'landing.hero_subtitle': 'The modern dropshipping platform. Empower your dropshippers. Grow together.',
    'landing.get_started': 'Get Started Free',
    'landing.watch_demo': 'Watch Demo',
    'landing.track_order': 'Track Order',
    'landing.sign_in': 'Sign In',
    'landing.features': 'Features',
    'landing.how_it_works': 'How It Works',
    'landing.testimonials': 'Testimonials',
    'landing.faq': 'FAQ',
    'landing.contact': 'Contact',
    
    // Activity Log
    'activity.login': 'Login',
    'activity.logout': 'Logout',
    'activity.order_placed': 'Order Placed',
    'activity.payout_request': 'Payout Request',
    'activity.profile_update': 'Profile Update',
    'activity.postpaid_repayment': 'Postpaid Repayment',
    'activity.crypto_payment': 'Crypto Payment',
    'activity.payment_details_update': 'Payment Details Update',
    'activity.kyc_submission': 'KYC Submission',
    'activity.current_session': 'Current Session',
    'activity.no_activity': 'No activity logs found',
    'activity.history_will_appear': 'Your login history will appear here',
    
    // Errors
    'error.generic': 'Something went wrong',
    'error.network': 'Network error. Please try again.',
    'error.unauthorized': 'Unauthorized access',
    'error.not_found': 'Not found',
    'error.try_again': 'Try Again',
  },
  hi: {
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.submit': 'जमा करें',
    'common.confirm': 'पुष्टि करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.refresh': 'रीफ्रेश',
    'common.close': 'बंद करें',
    'common.view': 'देखें',
    'common.download': 'डाउनलोड',
    'common.upload': 'अपलोड',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.actions': 'क्रियाएं',
    'common.status': 'स्थिति',
    'common.date': 'दिनांक',
    'common.amount': 'राशि',
    'common.total': 'कुल',
    'common.details': 'विवरण',
    'common.success': 'सफल',
    'common.error': 'त्रुटि',
    'common.warning': 'चेतावनी',
    'common.info': 'जानकारी',
    'common.all': 'सभी',
    'common.none': 'कोई नहीं',
    'common.select': 'चुनें',
    'common.clear': 'साफ़ करें',
    'common.apply': 'लागू करें',
    'common.reset': 'रीसेट करें',
    'common.update': 'अपडेट करें',
    'common.create': 'बनाएं',
    'common.add': 'जोड़ें',
    'common.remove': 'हटाएं',
    'common.copy': 'कॉपी करें',
    'common.share': 'साझा करें',
    'common.export': 'एक्सपोर्ट',
    'common.import': 'इम्पोर्ट',
    'common.print': 'प्रिंट',
    
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.storefront': 'मेरी दुकान',
    'nav.products': 'उत्पाद ब्राउज़ करें',
    'nav.orders': 'आदेश',
    'nav.payments': 'भुगतान',
    'nav.workspace': 'कार्यस्थान',
    'nav.support': 'सहायता',
    'nav.help': 'मदद',
    'nav.logout': 'लॉग आउट',
    'nav.settings': 'सेटिंग्स',
    'nav.home': 'होम',
    'nav.chat': 'चैट',
    'nav.notifications': 'सूचनाएं',
    
    // Profile
    'profile.title': 'मेरी प्रोफ़ाइल',
    'profile.description': 'अपनी प्रोफ़ाइल जानकारी, सुरक्षा सेटिंग्स और गतिविधि देखें।',
    'profile.appearance': 'दिखावट',
    'profile.appearance_desc': 'डैशबोर्ड के लिए अपनी पसंदीदा थीम चुनें',
    'profile.language': 'भाषा',
    'profile.language_desc': 'अपनी पसंदीदा भाषा चुनें',
    'profile.security': 'सुरक्षा',
    'profile.change_password': 'पासवर्ड बदलें',
    'profile.two_factor': 'दो-कारक प्रमाणीकरण',
    'profile.login_activity': 'लॉगिन गतिविधि',
    'profile.account_info': 'खाता जानकारी',
    'profile.email': 'ईमेल',
    'profile.name': 'नाम',
    'profile.phone': 'फ़ोन',
    'profile.address': 'पता',
    
    // Auth
    'auth.login': 'लॉग इन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.forgot_password': 'पासवर्ड भूल गए?',
    'auth.remember_me': 'मुझे याद रखें',
    'auth.welcome_back': 'वापसी पर स्वागत है',
    'auth.sign_in_desc': 'अपने डैशबोर्ड तक पहुंचने के लिए साइन इन करें',
    'auth.email_address': 'ईमेल पता',
    'auth.create_account': 'खाता बनाएं',
    'auth.already_have_account': 'पहले से खाता है?',
    'auth.dont_have_account': 'खाता नहीं है?',
    'auth.verify_email': 'ईमेल सत्यापित करें',
    'auth.resend_code': 'कोड पुनः भेजें',
    'auth.verification_code': 'सत्यापन कोड',
    
    // Dashboard
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.total_orders': 'कुल आदेश',
    'dashboard.pending_orders': 'लंबित आदेश',
    'dashboard.wallet_balance': 'वॉलेट बैलेंस',
    'dashboard.total_earnings': 'कुल कमाई',
    'dashboard.recent_orders': 'हाल के आदेश',
    'dashboard.quick_actions': 'त्वरित क्रियाएं',
    'dashboard.view_all': 'सभी देखें',
    'dashboard.todays_sales': 'आज की बिक्री',
    'dashboard.this_week': 'इस सप्ताह',
    'dashboard.this_month': 'इस महीने',
    'dashboard.growth': 'वृद्धि',
    'dashboard.revenue': 'राजस्व',
    'dashboard.profit': 'लाभ',
    'dashboard.commission': 'कमीशन',
    
    // Orders
    'orders.title': 'आदेश',
    'orders.new_order': 'नया आदेश',
    'orders.order_number': 'आदेश संख्या',
    'orders.status': 'स्थिति',
    'orders.customer': 'ग्राहक',
    'orders.amount': 'राशि',
    'orders.date': 'दिनांक',
    'orders.product': 'उत्पाद',
    'orders.quantity': 'मात्रा',
    'orders.price': 'मूल्य',
    'orders.total': 'कुल',
    'orders.pending': 'लंबित',
    'orders.processing': 'प्रोसेसिंग',
    'orders.completed': 'पूर्ण',
    'orders.cancelled': 'रद्द',
    'orders.paid': 'भुगतान हो गया',
    'orders.unpaid': 'अवैतनिक',
    'orders.view_order': 'आदेश देखें',
    'orders.track_order': 'आदेश ट्रैक करें',
    'orders.order_details': 'आदेश विवरण',
    'orders.customer_info': 'ग्राहक जानकारी',
    'orders.shipping_address': 'शिपिंग पता',
    'orders.payment_status': 'भुगतान स्थिति',
    'orders.order_history': 'आदेश इतिहास',
    'orders.no_orders': 'कोई आदेश नहीं मिला',
    'orders.place_order': 'आदेश दें',
    'orders.order_placed': 'आदेश सफलतापूर्वक दिया गया',
    'orders.pending_payment': 'भुगतान लंबित',
    'orders.paid_by_user': 'उपयोगकर्ता द्वारा भुगतान',
    'orders.postpaid_pending': 'पोस्टपेड लंबित',
    
    // Payments
    'payments.title': 'भुगतान',
    'payments.request_payout': 'भुगतान का अनुरोध करें',
    'payments.add_funds': 'फंड जोड़ें',
    'payments.transaction_history': 'लेन-देन इतिहास',
    'payments.balance': 'बैलेंस',
    'payments.available': 'उपलब्ध',
    'payments.pending': 'लंबित',
    'payments.payout_method': 'भुगतान विधि',
    'payments.bank_transfer': 'बैंक ट्रांसफर',
    'payments.upi': 'यूपीआई',
    'payments.crypto': 'क्रिप्टोकरेंसी',
    'payments.amount': 'राशि',
    'payments.fee': 'शुल्क',
    'payments.net_amount': 'शुद्ध राशि',
    'payments.request_date': 'अनुरोध तिथि',
    'payments.processed_date': 'प्रोसेस तिथि',
    'payments.status': 'स्थिति',
    'payments.approved': 'स्वीकृत',
    'payments.rejected': 'अस्वीकृत',
    'payments.processing': 'प्रोसेसिंग',
    'payments.completed': 'पूर्ण',
    'payments.no_transactions': 'कोई लेन-देन नहीं मिला',
    'payments.minimum_payout': 'न्यूनतम भुगतान',
    'payments.payment_details': 'भुगतान विवरण',
    'payments.bank_name': 'बैंक का नाम',
    'payments.account_number': 'खाता संख्या',
    'payments.ifsc_code': 'आईएफएससी कोड',
    'payments.account_holder': 'खाता धारक का नाम',
    'payments.upi_id': 'यूपीआई आईडी',
    'payments.wallet_address': 'वॉलेट पता',
    'payments.commission_earned': 'कमीशन अर्जित',
    'payments.payout_history': 'भुगतान इतिहास',
    
    // Products
    'products.title': 'उत्पाद',
    'products.browse': 'उत्पाद ब्राउज़ करें',
    'products.add_to_store': 'स्टोर में जोड़ें',
    'products.remove_from_store': 'स्टोर से हटाएं',
    'products.price': 'मूल्य',
    'products.base_price': 'बेस प्राइस',
    'products.selling_price': 'विक्रय मूल्य',
    'products.profit_margin': 'लाभ मार्जिन',
    'products.stock': 'स्टॉक',
    'products.in_stock': 'स्टॉक में',
    'products.out_of_stock': 'स्टॉक में नहीं',
    'products.category': 'श्रेणी',
    'products.description': 'विवरण',
    'products.sku': 'एसकेयू',
    'products.no_products': 'कोई उत्पाद नहीं मिला',
    'products.search_products': 'उत्पाद खोजें...',
    'products.my_products': 'मेरे उत्पाद',
    'products.all_products': 'सभी उत्पाद',
    
    // Storefront
    'storefront.title': 'मेरी दुकान',
    'storefront.setup': 'स्टोरफ्रंट सेटअप',
    'storefront.name': 'स्टोर का नाम',
    'storefront.slug': 'स्टोर URL',
    'storefront.banner': 'स्टोर बैनर',
    'storefront.products': 'स्टोर उत्पाद',
    'storefront.share': 'स्टोर साझा करें',
    'storefront.copy_link': 'लिंक कॉपी करें',
    'storefront.preview': 'स्टोर पूर्वावलोकन',
    'storefront.settings': 'स्टोर सेटिंग्स',
    
    // Support
    'support.title': 'सहायता',
    'support.chat': 'लाइव चैट',
    'support.tickets': 'सहायता टिकट',
    'support.faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'support.contact': 'संपर्क करें',
    'support.new_ticket': 'नया टिकट',
    'support.ticket_status': 'टिकट स्थिति',
    'support.open': 'खुला',
    'support.closed': 'बंद',
    'support.in_progress': 'प्रगति में',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.general': 'सामान्य',
    'settings.security': 'सुरक्षा',
    'settings.notifications': 'सूचनाएं',
    'settings.payment': 'भुगतान सेटिंग्स',
    'settings.save_changes': 'परिवर्तन सहेजें',
    
    // Landing Page
    'landing.hero_title': 'अपना ड्रॉपशिपिंग व्यवसाय शुरू करें',
    'landing.hero_subtitle': 'आधुनिक ड्रॉपशिपिंग प्लेटफॉर्म। अपने ड्रॉपशिपर्स को सशक्त बनाएं। साथ मिलकर बढ़ें।',
    'landing.get_started': 'मुफ्त में शुरू करें',
    'landing.watch_demo': 'डेमो देखें',
    'landing.track_order': 'ऑर्डर ट्रैक करें',
    'landing.sign_in': 'साइन इन करें',
    'landing.features': 'विशेषताएं',
    'landing.how_it_works': 'यह कैसे काम करता है',
    'landing.testimonials': 'प्रशंसापत्र',
    'landing.faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'landing.contact': 'संपर्क',
    
    // Activity Log
    'activity.login': 'लॉगिन',
    'activity.logout': 'लॉगआउट',
    'activity.order_placed': 'आदेश दिया गया',
    'activity.payout_request': 'भुगतान अनुरोध',
    'activity.profile_update': 'प्रोफ़ाइल अपडेट',
    'activity.postpaid_repayment': 'पोस्टपेड भुगतान',
    'activity.crypto_payment': 'क्रिप्टो भुगतान',
    'activity.payment_details_update': 'भुगतान विवरण अपडेट',
    'activity.kyc_submission': 'केवाईसी जमा',
    'activity.current_session': 'वर्तमान सत्र',
    'activity.no_activity': 'कोई गतिविधि लॉग नहीं मिला',
    'activity.history_will_appear': 'आपका लॉगिन इतिहास यहां दिखाई देगा',
    
    // Errors
    'error.generic': 'कुछ गलत हो गया',
    'error.network': 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
    'error.unauthorized': 'अनधिकृत पहुंच',
    'error.not_found': 'नहीं मिला',
    'error.try_again': 'पुनः प्रयास करें',
  },
  ta: {
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.save': 'சேமி',
    'common.cancel': 'ரத்துசெய்',
    'common.delete': 'நீக்கு',
    'common.edit': 'திருத்து',
    'common.submit': 'சமர்ப்பி',
    'common.confirm': 'உறுதிசெய்',
    'common.back': 'பின்',
    'common.next': 'அடுத்து',
    'common.search': 'தேடு',
    'common.filter': 'வடிகட்டி',
    'common.refresh': 'புதுப்பி',
    'common.close': 'மூடு',
    'common.view': 'காண்',
    'common.download': 'பதிவிறக்கு',
    'common.upload': 'பதிவேற்று',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
    'common.actions': 'செயல்கள்',
    'common.status': 'நிலை',
    'common.date': 'தேதி',
    'common.amount': 'தொகை',
    'common.total': 'மொத்தம்',
    'common.details': 'விவரங்கள்',
    'common.success': 'வெற்றி',
    'common.error': 'பிழை',
    'common.warning': 'எச்சரிக்கை',
    'common.info': 'தகவல்',
    'common.all': 'அனைத்தும்',
    'common.none': 'எதுவுமில்லை',
    'common.select': 'தேர்வுசெய்',
    'common.clear': 'அழி',
    'common.apply': 'பயன்படுத்து',
    'common.reset': 'மீட்டமை',
    'common.update': 'புதுப்பி',
    'common.create': 'உருவாக்கு',
    'common.add': 'சேர்',
    'common.remove': 'அகற்று',
    'common.copy': 'நகலெடு',
    'common.share': 'பகிர்',
    'common.export': 'ஏற்றுமதி',
    'common.import': 'இறக்குமதி',
    'common.print': 'அச்சிடு',
    
    // Navigation
    'nav.dashboard': 'டாஷ்போர்ட்',
    'nav.profile': 'சுயவிவரம்',
    'nav.storefront': 'என் கடை',
    'nav.products': 'பொருட்கள்',
    'nav.orders': 'ஆர்டர்கள்',
    'nav.payments': 'கொடுப்பனவுகள்',
    'nav.workspace': 'பணியிடம்',
    'nav.support': 'ஆதரவு',
    'nav.help': 'உதவி',
    'nav.logout': 'வெளியேறு',
    'nav.settings': 'அமைப்புகள்',
    'nav.home': 'முகப்பு',
    'nav.chat': 'அரட்டை',
    'nav.notifications': 'அறிவிப்புகள்',
    
    // Profile
    'profile.title': 'என் சுயவிவரம்',
    'profile.description': 'உங்கள் சுயவிவர தகவல், பாதுகாப்பு அமைப்புகள் மற்றும் செயல்பாட்டைக் காணலாம்.',
    'profile.appearance': 'தோற்றம்',
    'profile.appearance_desc': 'டாஷ்போர்டுக்கான உங்கள் விருப்பமான தீம் தேர்வுசெய்க',
    'profile.language': 'மொழி',
    'profile.language_desc': 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    'profile.security': 'பாதுகாப்பு',
    'profile.change_password': 'கடவுச்சொல்லை மாற்று',
    'profile.two_factor': 'இரண்டு-காரணி அங்கீகாரம்',
    'profile.login_activity': 'உள்நுழைவு செயல்பாடு',
    'profile.account_info': 'கணக்கு தகவல்',
    'profile.email': 'மின்னஞ்சல்',
    'profile.name': 'பெயர்',
    'profile.phone': 'தொலைபேசி',
    'profile.address': 'முகவரி',
    
    // Auth
    'auth.login': 'உள்நுழை',
    'auth.signup': 'பதிவுசெய்',
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'auth.remember_me': 'என்னை நினைவில் வை',
    'auth.welcome_back': 'மீண்டும் வரவேற்கிறோம்',
    'auth.sign_in_desc': 'உங்கள் டாஷ்போர்டை அணுக உள்நுழையவும்',
    'auth.email_address': 'மின்னஞ்சல் முகவரி',
    'auth.create_account': 'கணக்கை உருவாக்கு',
    'auth.already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'auth.dont_have_account': 'கணக்கு இல்லையா?',
    'auth.verify_email': 'மின்னஞ்சலை சரிபார்க்கவும்',
    'auth.resend_code': 'குறியீட்டை மீண்டும் அனுப்பு',
    'auth.verification_code': 'சரிபார்ப்பு குறியீடு',
    
    // Dashboard
    'dashboard.welcome': 'மீண்டும் வரவேற்கிறோம்',
    'dashboard.total_orders': 'மொத்த ஆர்டர்கள்',
    'dashboard.pending_orders': 'நிலுவை ஆர்டர்கள்',
    'dashboard.wallet_balance': 'வாலட் இருப்பு',
    'dashboard.total_earnings': 'மொத்த வருமானம்',
    'dashboard.recent_orders': 'சமீபத்திய ஆர்டர்கள்',
    'dashboard.quick_actions': 'விரைவு செயல்கள்',
    'dashboard.view_all': 'அனைத்தையும் காண்',
    'dashboard.todays_sales': 'இன்றைய விற்பனை',
    'dashboard.this_week': 'இந்த வாரம்',
    'dashboard.this_month': 'இந்த மாதம்',
    'dashboard.growth': 'வளர்ச்சி',
    'dashboard.revenue': 'வருவாய்',
    'dashboard.profit': 'லாபம்',
    'dashboard.commission': 'கமிஷன்',
    
    // Orders
    'orders.title': 'ஆர்டர்கள்',
    'orders.new_order': 'புதிய ஆர்டர்',
    'orders.order_number': 'ஆர்டர் எண்',
    'orders.status': 'நிலை',
    'orders.customer': 'வாடிக்கையாளர்',
    'orders.amount': 'தொகை',
    'orders.date': 'தேதி',
    'orders.product': 'பொருள்',
    'orders.quantity': 'அளவு',
    'orders.price': 'விலை',
    'orders.total': 'மொத்தம்',
    'orders.pending': 'நிலுவையில்',
    'orders.processing': 'செயலாக்கத்தில்',
    'orders.completed': 'முடிந்தது',
    'orders.cancelled': 'ரத்துசெய்யப்பட்டது',
    'orders.paid': 'பணம் செலுத்தப்பட்டது',
    'orders.unpaid': 'செலுத்தப்படவில்லை',
    'orders.view_order': 'ஆர்டரைக் காண்',
    'orders.track_order': 'ஆர்டரைக் கண்காணி',
    'orders.order_details': 'ஆர்டர் விவரங்கள்',
    'orders.customer_info': 'வாடிக்கையாளர் தகவல்',
    'orders.shipping_address': 'அனுப்பும் முகவரி',
    'orders.payment_status': 'கொடுப்பனவு நிலை',
    'orders.order_history': 'ஆர்டர் வரலாறு',
    'orders.no_orders': 'ஆர்டர்கள் இல்லை',
    'orders.place_order': 'ஆர்டர் செய்',
    'orders.order_placed': 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது',
    'orders.pending_payment': 'கொடுப்பனவு நிலுவையில்',
    'orders.paid_by_user': 'பயனரால் செலுத்தப்பட்டது',
    'orders.postpaid_pending': 'போஸ்ட்பெய்ட் நிலுவையில்',
    
    // Payments
    'payments.title': 'கொடுப்பனவுகள்',
    'payments.request_payout': 'கொடுப்பனவு கோரிக்கை',
    'payments.add_funds': 'நிதி சேர்க்க',
    'payments.transaction_history': 'பரிவர்த்தனை வரலாறு',
    'payments.balance': 'இருப்பு',
    'payments.available': 'கிடைக்கும்',
    'payments.pending': 'நிலுவையில்',
    'payments.payout_method': 'கொடுப்பனவு முறை',
    'payments.bank_transfer': 'வங்கி பரிமாற்றம்',
    'payments.upi': 'யுபிஐ',
    'payments.crypto': 'கிரிப்டோகரன்சி',
    'payments.amount': 'தொகை',
    'payments.fee': 'கட்டணம்',
    'payments.net_amount': 'நிகர தொகை',
    'payments.request_date': 'கோரிக்கை தேதி',
    'payments.processed_date': 'செயலாக்க தேதி',
    'payments.status': 'நிலை',
    'payments.approved': 'அங்கீகரிக்கப்பட்டது',
    'payments.rejected': 'நிராகரிக்கப்பட்டது',
    'payments.processing': 'செயலாக்கத்தில்',
    'payments.completed': 'முடிந்தது',
    'payments.no_transactions': 'பரிவர்த்தனைகள் இல்லை',
    'payments.minimum_payout': 'குறைந்தபட்ச கொடுப்பனவு',
    'payments.payment_details': 'கொடுப்பனவு விவரங்கள்',
    'payments.bank_name': 'வங்கி பெயர்',
    'payments.account_number': 'கணக்கு எண்',
    'payments.ifsc_code': 'ஐஎஃப்எஸ்சி குறியீடு',
    'payments.account_holder': 'கணக்கு வைத்திருப்பவர் பெயர்',
    'payments.upi_id': 'யுபிஐ ஐடி',
    'payments.wallet_address': 'வாலட் முகவரி',
    'payments.commission_earned': 'கமிஷன் சம்பாதித்தது',
    'payments.payout_history': 'கொடுப்பனவு வரலாறு',
    
    // Products
    'products.title': 'பொருட்கள்',
    'products.browse': 'பொருட்களை உலாவு',
    'products.add_to_store': 'கடையில் சேர்',
    'products.remove_from_store': 'கடையிலிருந்து அகற்று',
    'products.price': 'விலை',
    'products.base_price': 'அடிப்படை விலை',
    'products.selling_price': 'விற்பனை விலை',
    'products.profit_margin': 'லாப விகிதம்',
    'products.stock': 'இருப்பு',
    'products.in_stock': 'இருப்பில் உள்ளது',
    'products.out_of_stock': 'இருப்பில் இல்லை',
    'products.category': 'வகை',
    'products.description': 'விளக்கம்',
    'products.sku': 'எஸ்கேயு',
    'products.no_products': 'பொருட்கள் இல்லை',
    'products.search_products': 'பொருட்களைத் தேடு...',
    'products.my_products': 'என் பொருட்கள்',
    'products.all_products': 'அனைத்து பொருட்கள்',
    
    // Storefront
    'storefront.title': 'என் கடை',
    'storefront.setup': 'கடை அமைப்பு',
    'storefront.name': 'கடை பெயர்',
    'storefront.slug': 'கடை URL',
    'storefront.banner': 'கடை பேனர்',
    'storefront.products': 'கடை பொருட்கள்',
    'storefront.share': 'கடையைப் பகிர்',
    'storefront.copy_link': 'இணைப்பை நகலெடு',
    'storefront.preview': 'கடை முன்னோட்டம்',
    'storefront.settings': 'கடை அமைப்புகள்',
    
    // Support
    'support.title': 'ஆதரவு',
    'support.chat': 'நேரடி அரட்டை',
    'support.tickets': 'ஆதரவு டிக்கெட்டுகள்',
    'support.faq': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'support.contact': 'எங்களைத் தொடர்புகொள்ளுங்கள்',
    'support.new_ticket': 'புதிய டிக்கெட்',
    'support.ticket_status': 'டிக்கெட் நிலை',
    'support.open': 'திறந்தது',
    'support.closed': 'மூடப்பட்டது',
    'support.in_progress': 'நடப்பில்',
    
    // Settings
    'settings.title': 'அமைப்புகள்',
    'settings.general': 'பொது',
    'settings.security': 'பாதுகாப்பு',
    'settings.notifications': 'அறிவிப்புகள்',
    'settings.payment': 'கொடுப்பனவு அமைப்புகள்',
    'settings.save_changes': 'மாற்றங்களைச் சேமி',
    
    // Landing Page
    'landing.hero_title': 'உங்கள் டிராப்ஷிப்பிங் வணிகத்தைத் தொடங்குங்கள்',
    'landing.hero_subtitle': 'நவீன டிராப்ஷிப்பிங் தளம். உங்கள் டிராப்ஷிப்பர்களுக்கு அதிகாரம் அளியுங்கள். ஒன்றாக வளருங்கள்.',
    'landing.get_started': 'இலவசமாகத் தொடங்குங்கள்',
    'landing.watch_demo': 'டெமோ பாருங்கள்',
    'landing.track_order': 'ஆர்டரைக் கண்காணி',
    'landing.sign_in': 'உள்நுழைக',
    'landing.features': 'அம்சங்கள்',
    'landing.how_it_works': 'இது எப்படி வேலை செய்கிறது',
    'landing.testimonials': 'சான்றுகள்',
    'landing.faq': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'landing.contact': 'தொடர்பு',
    
    // Activity Log
    'activity.login': 'உள்நுழைவு',
    'activity.logout': 'வெளியேறுதல்',
    'activity.order_placed': 'ஆர்டர் வைக்கப்பட்டது',
    'activity.payout_request': 'கொடுப்பனவு கோரிக்கை',
    'activity.profile_update': 'சுயவிவர புதுப்பிப்பு',
    'activity.postpaid_repayment': 'போஸ்ட்பெய்ட் திருப்பிச்செலுத்துதல்',
    'activity.crypto_payment': 'கிரிப்டோ கொடுப்பனவு',
    'activity.payment_details_update': 'கொடுப்பனவு விவரங்கள் புதுப்பிப்பு',
    'activity.kyc_submission': 'கேஒய்சி சமர்ப்பிப்பு',
    'activity.current_session': 'தற்போதைய அமர்வு',
    'activity.no_activity': 'செயல்பாட்டு பதிவுகள் இல்லை',
    'activity.history_will_appear': 'உங்கள் உள்நுழைவு வரலாறு இங்கே தோன்றும்',
    
    // Errors
    'error.generic': 'ஏதோ தவறு நடந்தது',
    'error.network': 'நெட்வொர்க் பிழை. மீண்டும் முயற்சிக்கவும்.',
    'error.unauthorized': 'அங்கீகரிக்கப்படாத அணுகல்',
    'error.not_found': 'கிடைக்கவில்லை',
    'error.try_again': 'மீண்டும் முயற்சி',
  },
  te: {
    // Common
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.save': 'సేవ్ చేయి',
    'common.cancel': 'రద్దు చేయి',
    'common.delete': 'తొలగించు',
    'common.edit': 'సవరించు',
    'common.submit': 'సమర్పించు',
    'common.confirm': 'నిర్ధారించు',
    'common.back': 'వెనుకకు',
    'common.next': 'తదుపరి',
    'common.search': 'వెతుకు',
    'common.filter': 'ఫిల్టర్',
    'common.refresh': 'రిఫ్రెష్',
    'common.close': 'మూసివేయు',
    'common.view': 'చూడండి',
    'common.download': 'డౌన్‌లోడ్',
    'common.upload': 'అప్‌లోడ్',
    'common.yes': 'అవును',
    'common.no': 'కాదు',
    'common.actions': 'చర్యలు',
    'common.status': 'స్థితి',
    'common.date': 'తేదీ',
    'common.amount': 'మొత్తం',
    'common.total': 'మొత్తం',
    'common.details': 'వివరాలు',
    'common.success': 'విజయం',
    'common.error': 'లోపం',
    'common.warning': 'హెచ్చరిక',
    'common.info': 'సమాచారం',
    'common.all': 'అన్నీ',
    'common.none': 'ఏదీ కాదు',
    'common.select': 'ఎంచుకోండి',
    'common.clear': 'క్లియర్',
    'common.apply': 'వర్తించు',
    'common.reset': 'రీసెట్',
    'common.update': 'అప్‌డేట్',
    'common.create': 'సృష్టించు',
    'common.add': 'జోడించు',
    'common.remove': 'తొలగించు',
    'common.copy': 'కాపీ',
    'common.share': 'షేర్',
    'common.export': 'ఎక్స్‌పోర్ట్',
    'common.import': 'ఇంపోర్ట్',
    'common.print': 'ప్రింట్',
    
    // Navigation
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.profile': 'ప్రొఫైల్',
    'nav.storefront': 'నా స్టోర్',
    'nav.products': 'ఉత్పత్తులు',
    'nav.orders': 'ఆర్డర్లు',
    'nav.payments': 'చెల్లింపులు',
    'nav.workspace': 'వర్క్‌స్పేస్',
    'nav.support': 'మద్దతు',
    'nav.help': 'సహాయం',
    'nav.logout': 'లాగ్ అవుట్',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.home': 'హోమ్',
    'nav.chat': 'చాట్',
    'nav.notifications': 'నోటిఫికేషన్లు',
    
    // Profile
    'profile.title': 'నా ప్రొఫైల్',
    'profile.description': 'మీ ప్రొఫైల్ సమాచారం, భద్రతా సెట్టింగ్‌లు మరియు కార్యకలాపాలను చూడండి.',
    'profile.appearance': 'రూపం',
    'profile.appearance_desc': 'డాష్‌బోర్డ్ కోసం మీకు ఇష్టమైన థీమ్ ఎంచుకోండి',
    'profile.language': 'భాష',
    'profile.language_desc': 'మీకు ఇష్టమైన భాషను ఎంచుకోండి',
    'profile.security': 'భద్రత',
    'profile.change_password': 'పాస్‌వర్డ్ మార్చు',
    'profile.two_factor': 'రెండు-కారకాల ప్రమాణీకరణ',
    'profile.login_activity': 'లాగిన్ కార్యకలాపం',
    'profile.account_info': 'ఖాతా సమాచారం',
    'profile.email': 'ఇమెయిల్',
    'profile.name': 'పేరు',
    'profile.phone': 'ఫోన్',
    'profile.address': 'చిరునామా',
    
    // Auth
    'auth.login': 'లాగిన్',
    'auth.signup': 'సైన్ అప్',
    'auth.email': 'ఇమెయిల్',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
    'auth.remember_me': 'నన్ను గుర్తుంచుకో',
    'auth.welcome_back': 'తిరిగి స్వాగతం',
    'auth.sign_in_desc': 'మీ డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి',
    'auth.email_address': 'ఇమెయిల్ చిరునామా',
    'auth.create_account': 'ఖాతాను సృష్టించు',
    'auth.already_have_account': 'ఇప్పటికే ఖాతా ఉందా?',
    'auth.dont_have_account': 'ఖాతా లేదా?',
    'auth.verify_email': 'ఇమెయిల్‌ను ధృవీకరించండి',
    'auth.resend_code': 'కోడ్ మళ్ళీ పంపండి',
    'auth.verification_code': 'ధృవీకరణ కోడ్',
    
    // Dashboard
    'dashboard.welcome': 'తిరిగి స్వాగతం',
    'dashboard.total_orders': 'మొత్తం ఆర్డర్లు',
    'dashboard.pending_orders': 'పెండింగ్ ఆర్డర్లు',
    'dashboard.wallet_balance': 'వాలెట్ బ్యాలెన్స్',
    'dashboard.total_earnings': 'మొత్తం ఆదాయం',
    'dashboard.recent_orders': 'ఇటీవలి ఆర్డర్లు',
    'dashboard.quick_actions': 'త్వరిత చర్యలు',
    'dashboard.view_all': 'అన్నీ చూడండి',
    'dashboard.todays_sales': 'ఈ రోజు అమ్మకాలు',
    'dashboard.this_week': 'ఈ వారం',
    'dashboard.this_month': 'ఈ నెల',
    'dashboard.growth': 'వృద్ధి',
    'dashboard.revenue': 'ఆదాయం',
    'dashboard.profit': 'లాభం',
    'dashboard.commission': 'కమీషన్',
    
    // Orders
    'orders.title': 'ఆర్డర్లు',
    'orders.new_order': 'కొత్త ఆర్డర్',
    'orders.order_number': 'ఆర్డర్ నంబర్',
    'orders.status': 'స్థితి',
    'orders.customer': 'కస్టమర్',
    'orders.amount': 'మొత్తం',
    'orders.date': 'తేదీ',
    'orders.product': 'ఉత్పత్తి',
    'orders.quantity': 'పరిమాణం',
    'orders.price': 'ధర',
    'orders.total': 'మొత్తం',
    'orders.pending': 'పెండింగ్',
    'orders.processing': 'ప్రాసెసింగ్',
    'orders.completed': 'పూర్తయింది',
    'orders.cancelled': 'రద్దు చేయబడింది',
    'orders.paid': 'చెల్లించబడింది',
    'orders.unpaid': 'చెల్లించలేదు',
    'orders.view_order': 'ఆర్డర్ చూడండి',
    'orders.track_order': 'ఆర్డర్ ట్రాక్ చేయండి',
    'orders.order_details': 'ఆర్డర్ వివరాలు',
    'orders.customer_info': 'కస్టమర్ సమాచారం',
    'orders.shipping_address': 'షిప్పింగ్ చిరునామా',
    'orders.payment_status': 'చెల్లింపు స్థితి',
    'orders.order_history': 'ఆర్డర్ చరిత్ర',
    'orders.no_orders': 'ఆర్డర్లు కనుగొనబడలేదు',
    'orders.place_order': 'ఆర్డర్ చేయండి',
    'orders.order_placed': 'ఆర్డర్ విజయవంతంగా ఉంచబడింది',
    'orders.pending_payment': 'చెల్లింపు పెండింగ్',
    'orders.paid_by_user': 'వినియోగదారుచే చెల్లించబడింది',
    'orders.postpaid_pending': 'పోస్ట్‌పెయిడ్ పెండింగ్',
    
    // Payments
    'payments.title': 'చెల్లింపులు',
    'payments.request_payout': 'పేఅవుట్ అభ్యర్థన',
    'payments.add_funds': 'నిధులు జోడించండి',
    'payments.transaction_history': 'లావాదేవీ చరిత్ర',
    'payments.balance': 'బ్యాలెన్స్',
    'payments.available': 'అందుబాటులో',
    'payments.pending': 'పెండింగ్',
    'payments.payout_method': 'పేఅవుట్ పద్ధతి',
    'payments.bank_transfer': 'బ్యాంక్ బదిలీ',
    'payments.upi': 'యుపిఐ',
    'payments.crypto': 'క్రిప్టోకరెన్సీ',
    'payments.amount': 'మొత్తం',
    'payments.fee': 'ఫీజు',
    'payments.net_amount': 'నికర మొత్తం',
    'payments.request_date': 'అభ్యర్థన తేదీ',
    'payments.processed_date': 'ప్రాసెస్ తేదీ',
    'payments.status': 'స్థితి',
    'payments.approved': 'ఆమోదించబడింది',
    'payments.rejected': 'తిరస్కరించబడింది',
    'payments.processing': 'ప్రాసెసింగ్',
    'payments.completed': 'పూర్తయింది',
    'payments.no_transactions': 'లావాదేవీలు కనుగొనబడలేదు',
    'payments.minimum_payout': 'కనీస పేఅవుట్',
    'payments.payment_details': 'చెల్లింపు వివరాలు',
    'payments.bank_name': 'బ్యాంక్ పేరు',
    'payments.account_number': 'ఖాతా నంబర్',
    'payments.ifsc_code': 'ఐఎఫ్‌ఎస్‌సి కోడ్',
    'payments.account_holder': 'ఖాతాదారు పేరు',
    'payments.upi_id': 'యుపిఐ ఐడి',
    'payments.wallet_address': 'వాలెట్ చిరునామా',
    'payments.commission_earned': 'సంపాదించిన కమీషన్',
    'payments.payout_history': 'పేఅవుట్ చరిత్ర',
    
    // Products
    'products.title': 'ఉత్పత్తులు',
    'products.browse': 'ఉత్పత్తులను బ్రౌజ్ చేయండి',
    'products.add_to_store': 'స్టోర్‌కు జోడించండి',
    'products.remove_from_store': 'స్టోర్ నుండి తొలగించండి',
    'products.price': 'ధర',
    'products.base_price': 'బేస్ ధర',
    'products.selling_price': 'అమ్మకపు ధర',
    'products.profit_margin': 'లాభ మార్జిన్',
    'products.stock': 'స్టాక్',
    'products.in_stock': 'స్టాక్‌లో ఉంది',
    'products.out_of_stock': 'స్టాక్‌లో లేదు',
    'products.category': 'వర్గం',
    'products.description': 'వివరణ',
    'products.sku': 'ఎస్‌కేయు',
    'products.no_products': 'ఉత్పత్తులు కనుగొనబడలేదు',
    'products.search_products': 'ఉత్పత్తులను వెతకండి...',
    'products.my_products': 'నా ఉత్పత్తులు',
    'products.all_products': 'అన్ని ఉత్పత్తులు',
    
    // Storefront
    'storefront.title': 'నా స్టోర్',
    'storefront.setup': 'స్టోర్ సెటప్',
    'storefront.name': 'స్టోర్ పేరు',
    'storefront.slug': 'స్టోర్ URL',
    'storefront.banner': 'స్టోర్ బ్యానర్',
    'storefront.products': 'స్టోర్ ఉత్పత్తులు',
    'storefront.share': 'స్టోర్ షేర్ చేయండి',
    'storefront.copy_link': 'లింక్ కాపీ చేయండి',
    'storefront.preview': 'స్టోర్ ప్రివ్యూ',
    'storefront.settings': 'స్టోర్ సెట్టింగ్‌లు',
    
    // Support
    'support.title': 'మద్దతు',
    'support.chat': 'లైవ్ చాట్',
    'support.tickets': 'మద్దతు టికెట్లు',
    'support.faq': 'తరచుగా అడిగే ప్రశ్నలు',
    'support.contact': 'మమ్మల్ని సంప్రదించండి',
    'support.new_ticket': 'కొత్త టికెట్',
    'support.ticket_status': 'టికెట్ స్థితి',
    'support.open': 'తెరిచి ఉంది',
    'support.closed': 'మూసివేయబడింది',
    'support.in_progress': 'ప్రగతిలో ఉంది',
    
    // Settings
    'settings.title': 'సెట్టింగ్‌లు',
    'settings.general': 'సాధారణ',
    'settings.security': 'భద్రత',
    'settings.notifications': 'నోటిఫికేషన్లు',
    'settings.payment': 'చెల్లింపు సెట్టింగ్‌లు',
    'settings.save_changes': 'మార్పులను సేవ్ చేయండి',
    
    // Landing Page
    'landing.hero_title': 'మీ డ్రాప్‌షిప్పింగ్ వ్యాపారాన్ని ప్రారంభించండి',
    'landing.hero_subtitle': 'ఆధునిక డ్రాప్‌షిప్పింగ్ ప్లాట్‌ఫారమ్. మీ డ్రాప్‌షిప్పర్లకు అధికారం ఇవ్వండి. కలిసి పెరగండి.',
    'landing.get_started': 'ఉచితంగా ప్రారంభించండి',
    'landing.watch_demo': 'డెమో చూడండి',
    'landing.track_order': 'ఆర్డర్ ట్రాక్ చేయండి',
    'landing.sign_in': 'సైన్ ఇన్',
    'landing.features': 'ఫీచర్లు',
    'landing.how_it_works': 'ఇది ఎలా పని చేస్తుంది',
    'landing.testimonials': 'టెస్టిమోనియల్స్',
    'landing.faq': 'తరచుగా అడిగే ప్రశ్నలు',
    'landing.contact': 'సంప్రదించండి',
    
    // Activity Log
    'activity.login': 'లాగిన్',
    'activity.logout': 'లాగ్ అవుట్',
    'activity.order_placed': 'ఆర్డర్ ఉంచబడింది',
    'activity.payout_request': 'పేఅవుట్ అభ్యర్థన',
    'activity.profile_update': 'ప్రొఫైల్ అప్‌డేట్',
    'activity.postpaid_repayment': 'పోస్ట్‌పెయిడ్ తిరిగి చెల్లింపు',
    'activity.crypto_payment': 'క్రిప్టో చెల్లింపు',
    'activity.payment_details_update': 'చెల్లింపు వివరాల అప్‌డేట్',
    'activity.kyc_submission': 'కేవైసి సమర్పణ',
    'activity.current_session': 'ప్రస్తుత సెషన్',
    'activity.no_activity': 'కార్యకలాప లాగ్‌లు కనుగొనబడలేదు',
    'activity.history_will_appear': 'మీ లాగిన్ చరిత్ర ఇక్కడ కనిపిస్తుంది',
    
    // Errors
    'error.generic': 'ఏదో తప్పు జరిగింది',
    'error.network': 'నెట్‌వర్క్ లోపం. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    'error.unauthorized': 'అనధికార ప్రవేశం',
    'error.not_found': 'కనుగొనబడలేదు',
    'error.try_again': 'మళ్ళీ ప్రయత్నించండి',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('preferred-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('preferred-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  }, [language]);

  const currentLanguage = languages.find(l => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
